  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ehpta.hq010920;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2012-9-7
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class CalcUpperTransfeeVO extends SuperVO {
           
             public UFDouble fee;
             public String pk_corp;
             public String def5;
             public UFDouble outnum;
             public Integer dr;
             public String voperatorid;
             public String vapprovenote;
             public String def7;
             public String def14;
             public String eaddr;
             public UFDouble outmny;
             public UFDateTime ts;
             public String def6;
             public String def15;
             public UFBoolean settleflag;
             public String def18;
             public String def1;
             public UFDate edate;
             public String pk_invmandoc;
             public String def19;
             public String def20;
             public UFDate settledate;
             public UFDate sdate;
             public UFDouble dieselprice;
             public UFDate dmakedate;
             public String def17;
             public String def11;
             public String pk_billtype;
             public Integer vbillstatus;
             public String pk_busitype;
             public String def16;
             public String pk_transfee;
             public UFDouble rises;
             public String vbillno;
             public String pk_measdoc;
             public String def10;
             public String shipname;
             public String def13;
             public String def8;
             public String sourceno;
             public UFDate dapprovedate;
             public UFDouble num;
             public String vapproveid;
             public UFDouble recnum;
             public UFDouble paymny;
             public UFDouble transmny;
             public String def2;
             public String def12;
             public UFDouble numof;
             public String def4;
             public String def3;
             public String def9;
            
             public static final String  FEE="fee";   
             public static final String  PK_CORP="pk_corp";   
             public static final String  DEF5="def5";   
             public static final String  OUTNUM="outnum";   
             public static final String  DR="dr";   
             public static final String  VOPERATORID="voperatorid";   
             public static final String  VAPPROVENOTE="vapprovenote";   
             public static final String  DEF7="def7";   
             public static final String  DEF14="def14";   
             public static final String  EADDR="eaddr";   
             public static final String  OUTMNY="outmny";   
             public static final String  TS="ts";   
             public static final String  DEF6="def6";   
             public static final String  DEF15="def15";   
             public static final String  SETTLEFLAG="settleflag";   
             public static final String  DEF18="def18";   
             public static final String  DEF1="def1";   
             public static final String  EDATE="edate";   
             public static final String  PK_INVMANDOC="pk_invmandoc";   
             public static final String  DEF19="def19";   
             public static final String  DEF20="def20";   
             public static final String  SETTLEDATE="settledate";   
             public static final String  SDATE="sdate";   
             public static final String  DIESELPRICE="dieselprice";   
             public static final String  DMAKEDATE="dmakedate";   
             public static final String  DEF17="def17";   
             public static final String  DEF11="def11";   
             public static final String  PK_BILLTYPE="pk_billtype";   
             public static final String  VBILLSTATUS="vbillstatus";   
             public static final String  PK_BUSITYPE="pk_busitype";   
             public static final String  DEF16="def16";   
             public static final String  PK_TRANSFEE="pk_transfee";   
             public static final String  RISES="rises";   
             public static final String  VBILLNO="vbillno";   
             public static final String  PK_MEASDOC="pk_measdoc";   
             public static final String  DEF10="def10";   
             public static final String  SHIPNAME="shipname";   
             public static final String  DEF13="def13";   
             public static final String  DEF8="def8";   
             public static final String  SOURCENO="sourceno";   
             public static final String  DAPPROVEDATE="dapprovedate";   
             public static final String  NUM="num";   
             public static final String  VAPPROVEID="vapproveid";   
             public static final String  RECNUM="recnum";   
             public static final String  PAYMNY="paymny";   
             public static final String  TRANSMNY="transmny";   
             public static final String  DEF2="def2";   
             public static final String  DEF12="def12";   
             public static final String  NUMOF="numof";   
             public static final String  DEF4="def4";   
             public static final String  DEF3="def3";   
             public static final String  DEF9="def9";   
      
    
        /**
	   * 属性fee的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getFee() {
		 return fee;
	  }   
	  
     /**
	   * 属性fee的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newFee UFDouble
	   */
	public void setFee(UFDouble newFee) {
		
		fee = newFee;
	 } 	  
       
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性def5的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef5() {
		 return def5;
	  }   
	  
     /**
	   * 属性def5的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef5 String
	   */
	public void setDef5(String newDef5) {
		
		def5 = newDef5;
	 } 	  
       
        /**
	   * 属性outnum的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getOutnum() {
		 return outnum;
	  }   
	  
     /**
	   * 属性outnum的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newOutnum UFDouble
	   */
	public void setOutnum(UFDouble newOutnum) {
		
		outnum = newOutnum;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性voperatorid的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getVoperatorid() {
		 return voperatorid;
	  }   
	  
     /**
	   * 属性voperatorid的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newVoperatorid String
	   */
	public void setVoperatorid(String newVoperatorid) {
		
		voperatorid = newVoperatorid;
	 } 	  
       
        /**
	   * 属性vapprovenote的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getVapprovenote() {
		 return vapprovenote;
	  }   
	  
     /**
	   * 属性vapprovenote的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newVapprovenote String
	   */
	public void setVapprovenote(String newVapprovenote) {
		
		vapprovenote = newVapprovenote;
	 } 	  
       
        /**
	   * 属性def7的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef7() {
		 return def7;
	  }   
	  
     /**
	   * 属性def7的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef7 String
	   */
	public void setDef7(String newDef7) {
		
		def7 = newDef7;
	 } 	  
       
        /**
	   * 属性def14的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef14() {
		 return def14;
	  }   
	  
     /**
	   * 属性def14的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef14 String
	   */
	public void setDef14(String newDef14) {
		
		def14 = newDef14;
	 } 	  
       
        /**
	   * 属性eaddr的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getEaddr() {
		 return eaddr;
	  }   
	  
     /**
	   * 属性eaddr的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newEaddr String
	   */
	public void setEaddr(String newEaddr) {
		
		eaddr = newEaddr;
	 } 	  
       
        /**
	   * 属性outmny的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getOutmny() {
		 return outmny;
	  }   
	  
     /**
	   * 属性outmny的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newOutmny UFDouble
	   */
	public void setOutmny(UFDouble newOutmny) {
		
		outmny = newOutmny;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性def6的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef6() {
		 return def6;
	  }   
	  
     /**
	   * 属性def6的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef6 String
	   */
	public void setDef6(String newDef6) {
		
		def6 = newDef6;
	 } 	  
       
        /**
	   * 属性def15的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef15() {
		 return def15;
	  }   
	  
     /**
	   * 属性def15的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef15 String
	   */
	public void setDef15(String newDef15) {
		
		def15 = newDef15;
	 } 	  
       
        /**
	   * 属性settleflag的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFBoolean
	   */
	 public UFBoolean getSettleflag() {
		 return settleflag;
	  }   
	  
     /**
	   * 属性settleflag的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newSettleflag UFBoolean
	   */
	public void setSettleflag(UFBoolean newSettleflag) {
		
		settleflag = newSettleflag;
	 } 	  
       
        /**
	   * 属性def18的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef18() {
		 return def18;
	  }   
	  
     /**
	   * 属性def18的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef18 String
	   */
	public void setDef18(String newDef18) {
		
		def18 = newDef18;
	 } 	  
       
        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef1() {
		 return def1;
	  }   
	  
     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef1 String
	   */
	public void setDef1(String newDef1) {
		
		def1 = newDef1;
	 } 	  
       
        /**
	   * 属性edate的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDate
	   */
	 public UFDate getEdate() {
		 return edate;
	  }   
	  
     /**
	   * 属性edate的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newEdate UFDate
	   */
	public void setEdate(UFDate newEdate) {
		
		edate = newEdate;
	 } 	  
       
        /**
	   * 属性pk_invmandoc的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getPk_invmandoc() {
		 return pk_invmandoc;
	  }   
	  
     /**
	   * 属性pk_invmandoc的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPk_invmandoc String
	   */
	public void setPk_invmandoc(String newPk_invmandoc) {
		
		pk_invmandoc = newPk_invmandoc;
	 } 	  
       
        /**
	   * 属性def19的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef19() {
		 return def19;
	  }   
	  
     /**
	   * 属性def19的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef19 String
	   */
	public void setDef19(String newDef19) {
		
		def19 = newDef19;
	 } 	  
       
        /**
	   * 属性def20的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef20() {
		 return def20;
	  }   
	  
     /**
	   * 属性def20的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef20 String
	   */
	public void setDef20(String newDef20) {
		
		def20 = newDef20;
	 } 	  
       
        /**
	   * 属性settledate的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDate
	   */
	 public UFDate getSettledate() {
		 return settledate;
	  }   
	  
     /**
	   * 属性settledate的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newSettledate UFDate
	   */
	public void setSettledate(UFDate newSettledate) {
		
		settledate = newSettledate;
	 } 	  
       
        /**
	   * 属性sdate的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDate
	   */
	 public UFDate getSdate() {
		 return sdate;
	  }   
	  
     /**
	   * 属性sdate的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newSdate UFDate
	   */
	public void setSdate(UFDate newSdate) {
		
		sdate = newSdate;
	 } 	  
       
        /**
	   * 属性dieselprice的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getDieselprice() {
		 return dieselprice;
	  }   
	  
     /**
	   * 属性dieselprice的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDieselprice UFDouble
	   */
	public void setDieselprice(UFDouble newDieselprice) {
		
		dieselprice = newDieselprice;
	 } 	  
       
        /**
	   * 属性dmakedate的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDate
	   */
	 public UFDate getDmakedate() {
		 return dmakedate;
	  }   
	  
     /**
	   * 属性dmakedate的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDmakedate UFDate
	   */
	public void setDmakedate(UFDate newDmakedate) {
		
		dmakedate = newDmakedate;
	 } 	  
       
        /**
	   * 属性def17的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef17() {
		 return def17;
	  }   
	  
     /**
	   * 属性def17的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef17 String
	   */
	public void setDef17(String newDef17) {
		
		def17 = newDef17;
	 } 	  
       
        /**
	   * 属性def11的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef11() {
		 return def11;
	  }   
	  
     /**
	   * 属性def11的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef11 String
	   */
	public void setDef11(String newDef11) {
		
		def11 = newDef11;
	 } 	  
       
        /**
	   * 属性pk_billtype的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getPk_billtype() {
		 return pk_billtype;
	  }   
	  
     /**
	   * 属性pk_billtype的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPk_billtype String
	   */
	public void setPk_billtype(String newPk_billtype) {
		
		pk_billtype = newPk_billtype;
	 } 	  
       
        /**
	   * 属性vbillstatus的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return Integer
	   */
	 public Integer getVbillstatus() {
		 return vbillstatus;
	  }   
	  
     /**
	   * 属性vbillstatus的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newVbillstatus Integer
	   */
	public void setVbillstatus(Integer newVbillstatus) {
		
		vbillstatus = newVbillstatus;
	 } 	  
       
        /**
	   * 属性pk_busitype的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getPk_busitype() {
		 return pk_busitype;
	  }   
	  
     /**
	   * 属性pk_busitype的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPk_busitype String
	   */
	public void setPk_busitype(String newPk_busitype) {
		
		pk_busitype = newPk_busitype;
	 } 	  
       
        /**
	   * 属性def16的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef16() {
		 return def16;
	  }   
	  
     /**
	   * 属性def16的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef16 String
	   */
	public void setDef16(String newDef16) {
		
		def16 = newDef16;
	 } 	  
       
        /**
	   * 属性pk_transfee的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getPk_transfee() {
		 return pk_transfee;
	  }   
	  
     /**
	   * 属性pk_transfee的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPk_transfee String
	   */
	public void setPk_transfee(String newPk_transfee) {
		
		pk_transfee = newPk_transfee;
	 } 	  
       
        /**
	   * 属性rises的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getRises() {
		 return rises;
	  }   
	  
     /**
	   * 属性rises的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newRises UFDouble
	   */
	public void setRises(UFDouble newRises) {
		
		rises = newRises;
	 } 	  
       
        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }   
	  
     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {
		
		vbillno = newVbillno;
	 } 	  
       
        /**
	   * 属性pk_measdoc的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getPk_measdoc() {
		 return pk_measdoc;
	  }   
	  
     /**
	   * 属性pk_measdoc的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPk_measdoc String
	   */
	public void setPk_measdoc(String newPk_measdoc) {
		
		pk_measdoc = newPk_measdoc;
	 } 	  
       
        /**
	   * 属性def10的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef10() {
		 return def10;
	  }   
	  
     /**
	   * 属性def10的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef10 String
	   */
	public void setDef10(String newDef10) {
		
		def10 = newDef10;
	 } 	  
       
        /**
	   * 属性shipname的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getShipname() {
		 return shipname;
	  }   
	  
     /**
	   * 属性shipname的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newShipname String
	   */
	public void setShipname(String newShipname) {
		
		shipname = newShipname;
	 } 	  
       
        /**
	   * 属性def13的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef13() {
		 return def13;
	  }   
	  
     /**
	   * 属性def13的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef13 String
	   */
	public void setDef13(String newDef13) {
		
		def13 = newDef13;
	 } 	  
       
        /**
	   * 属性def8的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef8() {
		 return def8;
	  }   
	  
     /**
	   * 属性def8的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef8 String
	   */
	public void setDef8(String newDef8) {
		
		def8 = newDef8;
	 } 	  
       
        /**
	   * 属性sourceno的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getSourceno() {
		 return sourceno;
	  }   
	  
     /**
	   * 属性sourceno的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newSourceno String
	   */
	public void setSourceno(String newSourceno) {
		
		sourceno = newSourceno;
	 } 	  
       
        /**
	   * 属性dapprovedate的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDate
	   */
	 public UFDate getDapprovedate() {
		 return dapprovedate;
	  }   
	  
     /**
	   * 属性dapprovedate的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDapprovedate UFDate
	   */
	public void setDapprovedate(UFDate newDapprovedate) {
		
		dapprovedate = newDapprovedate;
	 } 	  
       
        /**
	   * 属性num的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getNum() {
		 return num;
	  }   
	  
     /**
	   * 属性num的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newNum UFDouble
	   */
	public void setNum(UFDouble newNum) {
		
		num = newNum;
	 } 	  
       
        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }   
	  
     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {
		
		vapproveid = newVapproveid;
	 } 	  
       
        /**
	   * 属性recnum的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getRecnum() {
		 return recnum;
	  }   
	  
     /**
	   * 属性recnum的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newRecnum UFDouble
	   */
	public void setRecnum(UFDouble newRecnum) {
		
		recnum = newRecnum;
	 } 	  
       
        /**
	   * 属性paymny的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getPaymny() {
		 return paymny;
	  }   
	  
     /**
	   * 属性paymny的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newPaymny UFDouble
	   */
	public void setPaymny(UFDouble newPaymny) {
		
		paymny = newPaymny;
	 } 	  
       
        /**
	   * 属性transmny的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getTransmny() {
		 return transmny;
	  }   
	  
     /**
	   * 属性transmny的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newTransmny UFDouble
	   */
	public void setTransmny(UFDouble newTransmny) {
		
		transmny = newTransmny;
	 } 	  
       
        /**
	   * 属性def2的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef2() {
		 return def2;
	  }   
	  
     /**
	   * 属性def2的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef2 String
	   */
	public void setDef2(String newDef2) {
		
		def2 = newDef2;
	 } 	  
       
        /**
	   * 属性def12的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef12() {
		 return def12;
	  }   
	  
     /**
	   * 属性def12的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef12 String
	   */
	public void setDef12(String newDef12) {
		
		def12 = newDef12;
	 } 	  
       
        /**
	   * 属性numof的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return UFDouble
	   */
	 public UFDouble getNumof() {
		 return numof;
	  }   
	  
     /**
	   * 属性numof的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newNumof UFDouble
	   */
	public void setNumof(UFDouble newNumof) {
		
		numof = newNumof;
	 } 	  
       
        /**
	   * 属性def4的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef4() {
		 return def4;
	  }   
	  
     /**
	   * 属性def4的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef4 String
	   */
	public void setDef4(String newDef4) {
		
		def4 = newDef4;
	 } 	  
       
        /**
	   * 属性def3的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef3() {
		 return def3;
	  }   
	  
     /**
	   * 属性def3的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef3 String
	   */
	public void setDef3(String newDef3) {
		
		def3 = newDef3;
	 } 	  
       
        /**
	   * 属性def9的Getter方法.
	   *
	   * 创建日期:2012-9-7
	   * @return String
	   */
	 public String getDef9() {
		 return def9;
	  }   
	  
     /**
	   * 属性def9的Setter方法.
	   *
	   * 创建日期:2012-9-7
	   * @param newDef9 String
	   */
	public void setDef9(String newDef9) {
		
		def9 = newDef9;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2012-9-7
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_transfee == null) {
			errFields.add(new String("pk_transfee"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-9-7
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-9-7
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_transfee";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2012-9-7
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ehpta_calc_upper_transfee";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-9-7
	  */
	public CalcUpperTransfeeVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2012-9-7
	 * @param newPk_transfee 主键值
	 */
	 public CalcUpperTransfeeVO(String newPk_transfee) {
		
		// 为主键字段赋值:
		 pk_transfee = newPk_transfee;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-9-7
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_transfee;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-9-7
	  * @param newPk_transfee  String    
	  */
	 public void setPrimaryKey(String newPk_transfee) {
				
				pk_transfee = newPk_transfee; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2012-9-7
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ehpta_calc_upper_transfee"; 
				
	 } 
} 
