/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ehpta.hq010402;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-7-10
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class SaleContractBVO extends SuperVO {

	private static final long serialVersionUID = 3039629622175075712L;
	
	public String def5;
	public Integer dr;
	public String def7;
	public String pk_invbasdoc;
	public String pk_priceweb;
	public String ts;
	public String def6;
	public String pk_contract;
	public String def10;
	public String pk_measdoc;
	public String memo;
	public String def8;
	public String invname;
	public String def1;
	public String pk_invspec;
	public UFDouble num;
	public String def2;
	public Integer numof;
	public String edate;
	public Integer execduration;
	public UFDouble totalnum;
	public String def4;
	public String durationunit;
	public UFDouble preprice;
	public String sdate;
	public String def3;
	public String def9;
	public String invspec;
	public String pk_contract_b;
	public UFDouble taxrate;

	public static final String DEF5 = "def5";
	public static final String DR = "dr";
	public static final String DEF7 = "def7";
	public static final String PK_INVBASDOC = "pk_invbasdoc";
	public static final String PK_PRICEWEB = "pk_priceweb";
	public static final String TS = "ts";
	public static final String DEF6 = "def6";
	public static final String PK_CONTRACT = "pk_contract";
	public static final String DEF10 = "def10";
	public static final String PK_MEASDOC = "pk_measdoc";
	public static final String MEMO = "memo";
	public static final String DEF8 = "def8";
	public static final String INVNAME = "invname";
	public static final String DEF1 = "def1";
	public static final String PAK_INVSPEC = "pak_invspec";
	public static final String NUM = "num";
	public static final String DEF2 = "def2";
	public static final String NUMOF = "numof";
	public static final String EDATE = "edate";
	public static final String EXECDURATION = "execduration";
	public static final String TOTALNUM = "totalnum";
	public static final String DEF4 = "def4";
	public static final String DURATIONUNIT = "durationunit";
	public static final String PREPRICE = "preprice";
	public static final String SDATE = "sdate";
	public static final String DEF3 = "def3";
	public static final String DEF9 = "def9";
	public static final String INVSPEC = "invspec";
	public static final String PK_CONTRACT_B = "pk_contract_b";

	
	public UFDouble getTaxrate() {
		return taxrate;
	}

	public void setTaxrate(UFDouble taxrate) {
		this.taxrate = taxrate;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性def7的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef7
	 *            String
	 */
	public void setDef7(String newDef7) {

		def7 = newDef7;
	}

	/**
	 * 属性pk_invbasdoc的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPk_invbasdoc() {
		return pk_invbasdoc;
	}

	/**
	 * 属性pk_invbasdoc的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_invbasdoc
	 *            String
	 */
	public void setPk_invbasdoc(String newPk_invbasdoc) {

		pk_invbasdoc = newPk_invbasdoc;
	}

	/**
	 * 属性pk_priceweb的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPk_priceweb() {
		return pk_priceweb;
	}

	/**
	 * 属性pk_priceweb的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_priceweb
	 *            String
	 */
	public void setPk_priceweb(String newPk_priceweb) {

		pk_priceweb = newPk_priceweb;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDateTime
	 */
	public String getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(String newTs) {

		ts = newTs;
	}

	/**
	 * 属性def6的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef6
	 *            String
	 */
	public void setDef6(String newDef6) {

		def6 = newDef6;
	}

	/**
	 * 属性pk_contract的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPk_contract() {
		return pk_contract;
	}

	/**
	 * 属性pk_contract的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_contract
	 *            String
	 */
	public void setPk_contract(String newPk_contract) {

		pk_contract = newPk_contract;
	}

	/**
	 * 属性def10的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef10
	 *            String
	 */
	public void setDef10(String newDef10) {

		def10 = newDef10;
	}

	/**
	 * 属性pk_measdoc的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPk_measdoc() {
		return pk_measdoc;
	}

	/**
	 * 属性pk_measdoc的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_measdoc
	 *            String
	 */
	public void setPk_measdoc(String newPk_measdoc) {

		pk_measdoc = newPk_measdoc;
	}

	/**
	 * 属性memo的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * 属性memo的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {

		memo = newMemo;
	}

	/**
	 * 属性def8的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef8
	 *            String
	 */
	public void setDef8(String newDef8) {

		def8 = newDef8;
	}

	/**
	 * 属性invname的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getInvname() {
		return invname;
	}

	/**
	 * 属性invname的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newInvname
	 *            String
	 */
	public void setInvname(String newInvname) {

		invname = newInvname;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性pak_invspec的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPk_invspec() {
		return pk_invspec;
	}

	/**
	 * 属性pak_invspec的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPak_invspec
	 *            String
	 */
	public void setPk_invspec(String newPk_invspec) {

		pk_invspec = newPk_invspec;
	}

	/**
	 * 属性num的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDouble
	 */
	public UFDouble getNum() {
		return num;
	}

	/**
	 * 属性num的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newNum
	 *            UFDouble
	 */
	public void setNum(UFDouble newNum) {

		num = newNum;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性numof的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDouble
	 */
	public Integer getNumof() {
		return numof;
	}

	/**
	 * 属性numof的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newNumof
	 *            UFDouble
	 */
	public void setNumof(Integer newNumof) {

		numof = newNumof;
	}

	/**
	 * 属性edate的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDate
	 */
	public String getEdate() {
		return edate;
	}

	/**
	 * 属性edate的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newEdate
	 *            UFDate
	 */
	public void setEdate(String newEdate) {

		edate = newEdate;
	}

	/**
	 * 属性execduration的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return Integer
	 */
	public Integer getExecduration() {
		return execduration;
	}

	/**
	 * 属性execduration的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newExecduration
	 *            Integer
	 */
	public void setExecduration(Integer newExecduration) {

		execduration = newExecduration;
	}

	/**
	 * 属性totalnum的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDouble
	 */
	public UFDouble getTotalnum() {
		return totalnum;
	}

	/**
	 * 属性totalnum的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newTotalnum
	 *            UFDouble
	 */
	public void setTotalnum(UFDouble newTotalnum) {

		totalnum = newTotalnum;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性durationunit的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDurationunit() {
		return durationunit;
	}

	/**
	 * 属性durationunit的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDurationunit
	 *            String
	 */
	public void setDurationunit(String newDurationunit) {

		durationunit = newDurationunit;
	}

	/**
	 * 属性preprice的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPreprice() {
		return preprice;
	}

	/**
	 * 属性preprice的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPreprice
	 *            UFDouble
	 */
	public void setPreprice(UFDouble newPreprice) {

		preprice = newPreprice;
	}

	/**
	 * 属性sdate的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return UFDate
	 */
	public String getSdate() {
		return sdate;
	}

	/**
	 * 属性sdate的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newSdate
	 *            UFDate
	 */
	public void setSdate(String newSdate) {

		sdate = newSdate;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性def9的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newDef9
	 *            String
	 */
	public void setDef9(String newDef9) {

		def9 = newDef9;
	}

	/**
	 * 属性invspec的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getInvspec() {
		return invspec;
	}

	/**
	 * 属性invspec的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newInvspec
	 *            String
	 */
	public void setInvspec(String newInvspec) {

		invspec = newInvspec;
	}

	/**
	 * 属性pk_contract_b的Getter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPk_contract_b() {
		return pk_contract_b;
	}

	/**
	 * 属性pk_contract_b的Setter方法.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_contract_b
	 *            String
	 */
	public void setPk_contract_b(String newPk_contract_b) {

		pk_contract_b = newPk_contract_b;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	@SuppressWarnings("unchecked")
	public void validate() throws ValidationException {

		@SuppressWarnings("rawtypes")
		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_contract_b == null) {
			errFields.add(new String("pk_contract_b"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-7-10
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "pk_contract";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-7-10
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_contract_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-7-10
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "ehpta_sale_contract_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-7-10
	 */
	public SaleContractBVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_contract_b
	 *            主键值
	 */
	public SaleContractBVO(String newPk_contract_b) {

		// 为主键字段赋值:
		pk_contract_b = newPk_contract_b;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_contract_b;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @param newPk_contract_b
	 *            String
	 */
	public void setPrimaryKey(String newPk_contract_b) {

		pk_contract_b = newPk_contract_b;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-7-10
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "ehpta_sale_contract_b";

	}
}
