/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.vo.hi.hi_305;

import java.util.ArrayList;

import nc.vo.hr.utils.ml.HRPubRes;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * 此处插入类型说明。
 * 
 * 创建日期：(2002-3-28)
 * @author：zhonghaijing
 */ 
public class SglstatHHeaderVO extends CircularlyAccessibleValueObject {

	public String m_pk_sglstat_h;
	public String m_sglstatnum;
	public String m_sglstatname;
	public String m_pk_corp;
	public String m_cUserId;
	public Integer m_psnclscope;

	/**
	 *     描述上面属性的FieldObjects。主要用于系统工具中，
	 * 业务代码中不会用到下面的FieldObjects。
	 */
	private static StringField m_pk_sglstat_hField;
	private static StringField m_sglstatnumField;
	private static StringField m_sglstatnameField;
	private static StringField m_pk_corpField;
	private static StringField m_cUserIdField;
	private static IntegerField m_psnclscopeField;
/**
 * 使用主键字段进行初始化的构造子。
 *
 * 创建日期：(2002-3-28)
 */
public SglstatHHeaderVO() {

}
/**
 * 使用主键进行初始化的构造子。
 *
 * 创建日期：(2002-3-28)
 * @param ??fieldNameForMethod?? 主键值
 */
public SglstatHHeaderVO(String newPk_sglstat_h) {

	// 为主键字段赋值:
	m_pk_sglstat_h = newPk_sglstat_h;
}
/**
 * 根类Object的方法,克隆这个VO对象。
 *
 * 创建日期：(2002-3-28)
 */
public Object clone() {

	// 复制基类内容并创建新的VO对象：
	Object o = null;
	try {
		o = super.clone();
	} catch (Exception e) {}
	SglstatHHeaderVO sglstatH = (SglstatHHeaderVO)o;

	// 你在下面复制本VO对象的所有属性：

	return sglstatH;
}
/**
 * 返回数值对象的显示名称。
 *
 * 创建日期：(2002-3-28)
 * @return java.lang.String 返回数值对象的显示名称。
 */
public String getEntityName() {

	return "SglstatH";
}
/**
 * 返回对象标识，用来唯一定位对象。
 *
 * 创建日期：(2002-3-28)
 * @return String
 */
public String getPrimaryKey() {

	return m_pk_sglstat_h;
}
/**
 * 设置对象标识，用来唯一定位对象。
 *
 * 创建日期：(2002-3-28)
 * @param m_pk_sglstat_h String 
 */
public void setPrimaryKey(String newPk_sglstat_h) {

	m_pk_sglstat_h = newPk_sglstat_h;
}
/**
 * 属性m_pk_sglstat_h的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return String
 */
public String getPk_sglstat_h() {
	return m_pk_sglstat_h;
}
/**
 * 属性m_sglstatnum的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return String
 */
public String getSglstatnum() {
	return m_sglstatnum;
}
/**
 * 属性m_sglstatname的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return String
 */
public String getSglstatname() {
	return m_sglstatname;
}
/**
 * 属性m_pk_corp的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return String
 */
public String getPk_corp() {
	return m_pk_corp;
}
/**
 * 属性m_cUserId的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return String
 */
public String getCUserId() {
	return m_cUserId;
}
/**
 * 属性m_psnclscope的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return Integer
 */
public Integer getPsnclscope() {
	return m_psnclscope;
}
/**
 * 属性m_pk_sglstat_h的setter方法。
 *
 * 创建日期：(2002-3-28)
 * @param newM_pk_sglstat_h String
 */
public void setPk_sglstat_h(String newPk_sglstat_h) {

	m_pk_sglstat_h = newPk_sglstat_h;
}
/**
 * 属性m_sglstatnum的setter方法。
 *
 * 创建日期：(2002-3-28)
 * @param newM_sglstatnum String
 */
public void setSglstatnum(String newSglstatnum) {

	m_sglstatnum = newSglstatnum;
}
/**
 * 属性m_sglstatname的setter方法。
 *
 * 创建日期：(2002-3-28)
 * @param newM_sglstatname String
 */
public void setSglstatname(String newSglstatname) {

	m_sglstatname = newSglstatname;
}
/**
 * 属性m_pk_corp的setter方法。
 *
 * 创建日期：(2002-3-28)
 * @param newM_pk_corp String
 */
public void setPk_corp(String newPk_corp) {

	m_pk_corp = newPk_corp;
}
/**
 * 属性m_cUserId的setter方法。
 *
 * 创建日期：(2002-3-28)
 * @param newM_cUserId String
 */
public void setCUserId(String newCUserId) {

	m_cUserId = newCUserId;
}
/**
 * 属性m_psnclscope的setter方法。
 *
 * 创建日期：(2002-3-28)
 * @param newM_psnclscope Integer
 */
public void setPsnclscope(Integer newPsnclscope) {

	m_psnclscope = newPsnclscope;
}
/**
 * 验证对象各属性之间的数据逻辑正确性。
 *
 * 创建日期：(2002-3-28)
 * @exception nc.vo.pub.ValidationException 如果验证失败，抛出
 *     ValidationException，对错误进行解释。
 */
public void validate() throws ValidationException {

	ArrayList errFields = new ArrayList(); // errFields record those null fields that cannot be null.
	// 检查是否为不允许空的字段赋了空值，你可能需要修改下面的提示信息：
	if (m_pk_sglstat_h == null) {
		errFields.add(new String("m_pk_sglstat_h"));
	}
	// construct the exception message:
	StringBuffer message = new StringBuffer();
	message.append(nc.vo.bd.IBDMsg.MSG_NULL_FIELD);//message.append("下列字段不能为空：");
	if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");//message.append("、");
			message.append(temp[i]);
		}
		// throw the exception:
		throw new NullFieldException(message.toString());
	}
}
/**
 * <p>需要在一个循环中访问的属性的名称数组。
 * <p>
 * 创建日期：(??Date??)
 * @return java.lang.String[]
 */
public java.lang.String[] getAttributeNames() {

	return new String[]{ "sglstatnum", "sglstatname", "pk_corp", "cUserId", "psnclscope" };
}
/**
 *  <p>根据一个属性名称字符串该属性的值。
 *  <p>
 * 创建日期：(2002-3-28)
 * @param key java.lang.String
 */
public Object getAttributeValue(String attributeName) {

	if (attributeName.equals("pk_sglstat_h")) {
		return m_pk_sglstat_h;
	}
	else if (attributeName.equals("sglstatnum")) {
		return m_sglstatnum;
	}
	else if (attributeName.equals("sglstatname")) {
		return m_sglstatname;
	}
	else if (attributeName.equals("pk_corp")) {
		return m_pk_corp;
	}
	else if (attributeName.equals("cUserId")) {
		return m_cUserId;
	}
	else if (attributeName.equals("psnclscope")) {
		return m_psnclscope;
	}
	return null;
}
/**
 *  <p>对参数name对型的属性设置值。
 *  <p>
 * 创建日期：(2002-3-28)
 * @param key java.lang.String
 */
public void setAttributeValue(String name, Object value) {

	try {
		if (name.equals("pk_sglstat_h")) {
			m_pk_sglstat_h = (String) value;
		}
		else if (name.equals("sglstatnum")) {
			m_sglstatnum = (String) value;
		}
		else if (name.equals("sglstatname")) {
			m_sglstatname = (String) value;
		}
		else if (name.equals("pk_corp")) {
			m_pk_corp = (String) value;
		}
		else if (name.equals("cUserId")) {
			m_cUserId = (String) value;
		}
		else if (name.equals("psnclscope")) {
			m_psnclscope = (Integer) value;
		}
	}
	catch (ClassCastException e) {
		throw new ClassCastException(HRPubRes.getClassCastErrMsg(name,value));//throw new ClassCastException("setAttributeValue方法中为 " + name + " 赋值时类型转换错误！（值：" + value + "）");
	}
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getPk_sglstat_hField() {

	if(m_pk_sglstat_hField == null){
		try{
			m_pk_sglstat_hField = new StringField();
			// 属性的名称
			m_pk_sglstat_hField.setName("pk_sglstat_h");
			// 属性的描述
			m_pk_sglstat_hField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_pk_sglstat_hField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getSglstatnumField() {

	if(m_sglstatnumField == null){
		try{
			m_sglstatnumField = new StringField();
			// 属性的名称
			m_sglstatnumField.setName("sglstatnum");
			// 属性的描述
			m_sglstatnumField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_sglstatnumField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getSglstatnameField() {

	if(m_sglstatnameField == null){
		try{
			m_sglstatnameField = new StringField();
			// 属性的名称
			m_sglstatnameField.setName("sglstatname");
			// 属性的描述
			m_sglstatnameField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_sglstatnameField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getPk_corpField() {

	if(m_pk_corpField == null){
		try{
			m_pk_corpField = new StringField();
			// 属性的名称
			m_pk_corpField.setName("pk_corp");
			// 属性的描述
			m_pk_corpField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_pk_corpField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getCUserIdField() {

	if(m_cUserIdField == null){
		try{
			m_cUserIdField = new StringField();
			// 属性的名称
			m_cUserIdField.setName("cUserId");
			// 属性的描述
			m_cUserIdField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_cUserIdField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject
 */
public static IntegerField getPsnclscopeField() {

	if(m_psnclscopeField == null){
		try{
			m_psnclscopeField = new IntegerField();
			// 属性的名称
			m_psnclscopeField.setName("psnclscope");
			// 属性的描述
			m_psnclscopeField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_psnclscopeField;
}
/**
 * 返回这个ValueObject类的所有FieldObject对象的集合。
 *
 * 创建日期：(2002-3-28)
 * @return nc.vo.pub.FieldObject[]
 */
public FieldObject[] getFields() {

	FieldObject[] fields = {getPk_sglstat_hField(), getSglstatnumField(), getSglstatnameField(), getPk_corpField(), getCUserIdField(), getPsnclscopeField()};

	return fields;
}
}