package nc.itf.hr.hsmodify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Oct 26 13:46:18 CST 2009
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV")
@XmlSeeAlso({ObjectFactory.class})
public interface UFIDAU9CBOHRCBOHRSVIPersonModifySV {

    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "nc.itf.hr.hsmodify.DoResponse")
    @Action(input = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/Do", output = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/DoResponse", fault = {@FaultAction(className = UFIDAU9CBOHRCBOHRSVIPersonModifySVDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/DoExceptionFault"),@FaultAction(className = UFIDAU9CBOHRCBOHRSVIPersonModifySVDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/DoExceptionBaseFault"),@FaultAction(className = UFIDAU9CBOHRCBOHRSVIPersonModifySVDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/DoServiceLostExceptionFault"),@FaultAction(className = UFIDAU9CBOHRCBOHRSVIPersonModifySVDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/DoServiceExceptionFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "nc.itf.hr.hsmodify.Do")
    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.CBO.HR.CBOHRSV.IPersonModifySV/Do")
    public void _do(
        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "personDTOs", targetNamespace = "http://www.UFIDA.org")
        nc.itf.hr.hsmodify.ArrayOfUFIDAU9CBOHRCBOHRSVPersonDTOData personDTOs,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<java.lang.String> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<ArrayOfMessageBase> outMessages
    ) throws UFIDAU9CBOHRCBOHRSVIPersonModifySVDoExceptionFaultFaultMessage, UFIDAU9CBOHRCBOHRSVIPersonModifySVDoExceptionBaseFaultFaultMessage, UFIDAU9CBOHRCBOHRSVIPersonModifySVDoServiceLostExceptionFaultFaultMessage, UFIDAU9CBOHRCBOHRSVIPersonModifySVDoServiceExceptionFaultFaultMessage;
}
