prompt Importing table bd_billtype...
set feedback off
set define off
insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '余额调整单', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010403', null, null, null, null, 'nc.ui.ehpta.hq010403.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010403', null, 'HQ07', null, 'ehpta', '2012-07-22 20:35:17', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '仓储费结算单', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010202', null, null, null, null, 'nc.ui.ehpta.hq010202.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010202', null, 'HQ05', null, 'ehpta', '2012-07-09 14:28:00', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, 'PTA挂结价维护', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010301', null, null, null, null, 'nc.ui.ehpta.hq010301.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010301', null, 'HQ03', null, 'ehpta', '2012-07-04 13:11:09', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, null, '长单合同', 'N', 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010402', null, null, null, null, 'nc.ui.ehpta.hq010402.ClientUICheckRule', null, null, 'N', 'Y', 'N', null, 'HQ010402', null, 'HQ06', 'nc.bs.ehpta.dmo.SaleContractDMO', 'ehpta', '2012-07-13 14:48:29', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, 'PTA仓储合同', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010201', null, null, null, null, 'nc.ui.ehpta.hq010201.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010201', null, 'HQ01', null, 'ehpta', '2012-07-02 11:27:11', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, null, '现货合同', 'N', 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010401', null, null, null, null, 'nc.ui.ehpta.hq010401.ClientUICheckRule', null, null, 'N', 'Y', 'N', null, 'HQ010401', null, 'HQ04', 'nc.bs.ehpta.dmo.SpotContractDMO', 'ehpta', '2012-07-13 14:48:48', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, 'PTA运输合同', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010101', null, null, null, null, 'nc.ui.ehpta.hq010101.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010101', null, 'HQ02', null, 'ehpta', '2012-07-02 08:02:36', null, null);

prompt Done.
