/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ehpta.hq010101;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-7-2
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class EhptaTransportVO extends SuperVO {
	public String shipperparty;
	public String securedparty;
	public String shipperowner;
	public String pk_corp;
	public UFDate startdate;
	public String def5;
	public UFDate enddate;
	public String pk_transport;
	public Integer dr;
	public UFDate singledate;
	public String voperatorid;
	public String vapprovenote;
	public String pk_billtype;
	public Integer vbillstatus;
	public String def7;
	public UFBoolean stopstatus;
	public UFDate stopdate;
	public String pk_shipperowner;
	public String pk_shipperparty;
	public String pk_busitype;
	public UFDate ts;
	public String def6;
	public String vbillno;
	public String def10;
	public UFDate qianyuedate;
	public String remarks;
	public String def8;
	public String contracttype;
	public String def1;
	public UFDate dapprovedate;
	public String vapproveid;
	public String def2;
	public String def4;
	public String pk_securedparty;
	public String def3;
	public String def9;

	public static final String PK_CORP = "pk_corp";
	public static final String STARTDATE = "startdate";
	public static final String DEF5 = "def5";
	public static final String ENDDATE = "enddate";
	public static final String PK_TRANSPORT = "pk_transport";
	public static final String DR = "dr";
	public static final String SINGLEDATE = "singledate";
	public static final String VOPERATORID = "voperatorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String DEF7 = "def7";
	public static final String STOPSTATUS = "stopstatus";
	public static final String STOPDATE = "stopdate";
	public static final String PK_SHIPPEROWNER = "pk_shipperowner";
	public static final String PK_SHIPPERPARTY = "pk_shipperparty";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String TS = "ts";
	public static final String DEF6 = "def6";
	public static final String VBILLNO = "vbillno";
	public static final String DEF10 = "def10";
	public static final String QIANYUEDATE = "qianyuedate";
	public static final String REMARKS = "remarks";
	public static final String DEF8 = "def8";
	public static final String CONTRACTTYPE = "contracttype";
	public static final String DEF1 = "def1";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String DEF4 = "def4";
	public static final String PK_SECUREDPARTY = "pk_securedparty";
	public static final String DEF3 = "def3";
	public static final String DEF9 = "def9";
	public static final String SHIIPPERPARTY = "shipperparty";
	public static String SECUREDPARTY = "securedparty";
	public static String SHIPPEROWNER = "shipperowner";

	public String getShipperparty() {
		return shipperparty;
	}

	public void setShipperparty(String newshipperparty) {
		shipperparty = newshipperparty;
	}

	public String getSecuredparty() {
		return securedparty;
	}

	public void setSecuredparty(String newsecuredparty) {
		securedparty = newsecuredparty;
	}

	public String getShipperowner() {
		return shipperowner;
	}

	public void setShipperowner(String newshipperowner) {
		shipperowner = newshipperowner;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性startdate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getStartdate() {
		return startdate;
	}

	/**
	 * 属性startdate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStartdate
	 *            UFDate
	 */
	public void setStartdate(UFDate newStartdate) {

		startdate = newStartdate;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性enddate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getEnddate() {
		return enddate;
	}

	/**
	 * 属性enddate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newEnddate
	 *            UFDate
	 */
	public void setEnddate(UFDate newEnddate) {

		enddate = newEnddate;
	}

	/**
	 * 属性pk_transport的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_transport() {
		return pk_transport;
	}

	/**
	 * 属性pk_transport的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_transport
	 *            String
	 */
	public void setPk_transport(String newPk_transport) {

		pk_transport = newPk_transport;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性singledate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getSingledate() {
		return singledate;
	}

	/**
	 * 属性singledate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newSingledate
	 *            UFDate
	 */
	public void setSingledate(UFDate newSingledate) {

		singledate = newSingledate;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性pk_billtype的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_billtype() {
		return pk_billtype;
	}

	/**
	 * 属性pk_billtype的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_billtype
	 *            String
	 */
	public void setPk_billtype(String newPk_billtype) {

		pk_billtype = newPk_billtype;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性def7的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef7
	 *            String
	 */
	public void setDef7(String newDef7) {

		def7 = newDef7;
	}

	/**
	 * 属性stopstatus的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getStopstatus() {
		return stopstatus;
	}

	/**
	 * 属性stopstatus的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStopstatus
	 *            UFBoolean
	 */
	public void setStopstatus(UFBoolean newStopstatus) {

		stopstatus = newStopstatus;
	}

	/**
	 * 属性stopdate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getStopdate() {
		return stopdate;
	}

	/**
	 * 属性stopdate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStopdate
	 *            UFDate
	 */
	public void setStopdate(UFDate newStopdate) {

		stopdate = newStopdate;
	}

	/**
	 * 属性pk_shipperowner的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_shipperowner() {
		return pk_shipperowner;
	}

	/**
	 * 属性pk_shipperowner的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_shipperowner
	 *            String
	 */
	public void setPk_shipperowner(String newPk_shipperowner) {

		pk_shipperowner = newPk_shipperowner;
	}

	/**
	 * 属性pk_shipperparty的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_shipperparty() {
		return pk_shipperparty;
	}

	/**
	 * 属性pk_shipperparty的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_shipperparty
	 *            String
	 */
	public void setPk_shipperparty(String newPk_shipperparty) {

		pk_shipperparty = newPk_shipperparty;
	}

	/**
	 * 属性pk_busitype的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_busitype() {
		return pk_busitype;
	}

	/**
	 * 属性pk_busitype的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_busitype
	 *            String
	 */
	public void setPk_busitype(String newPk_busitype) {

		pk_busitype = newPk_busitype;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDateTime
	 */
	public UFDate getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDate newTs) {

		ts = newTs;
	}

	/**
	 * 属性def6的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef6
	 *            String
	 */
	public void setDef6(String newDef6) {

		def6 = newDef6;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性def10的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef10
	 *            String
	 */
	public void setDef10(String newDef10) {

		def10 = newDef10;
	}

	/**
	 * 属性qianyuedate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getQianyuedate() {
		return qianyuedate;
	}

	/**
	 * 属性qianyuedate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newQianyuedate
	 *            UFDate
	 */
	public void setQianyuedate(UFDate newQianyuedate) {

		qianyuedate = newQianyuedate;
	}

	/**
	 * 属性remarks的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * 属性remarks的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newRemarks
	 *            String
	 */
	public void setRemarks(String newRemarks) {

		remarks = newRemarks;
	}

	/**
	 * 属性def8的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef8
	 *            String
	 */
	public void setDef8(String newDef8) {

		def8 = newDef8;
	}

	/**
	 * 属性contracttype的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getContracttype() {
		return contracttype;
	}

	/**
	 * 属性contracttype的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newContracttype
	 *            String
	 */
	public void setContracttype(String newContracttype) {

		contracttype = newContracttype;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性pk_securedparty的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_securedparty() {
		return pk_securedparty;
	}

	/**
	 * 属性pk_securedparty的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_securedparty
	 *            String
	 */
	public void setPk_securedparty(String newPk_securedparty) {

		pk_securedparty = newPk_securedparty;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性def9的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef9
	 *            String
	 */
	public void setDef9(String newDef9) {

		def9 = newDef9;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_transport == null) {
			errFields.add(new String("pk_transport"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_transport";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "ehpta_transport";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-7-2
	 */
	public EhptaTransportVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_transport
	 *            主键值
	 */
	public EhptaTransportVO(String newPk_transport) {

		// 为主键字段赋值:
		pk_transport = newPk_transport;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_transport;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_transport
	 *            String
	 */
	public void setPrimaryKey(String newPk_transport) {

		pk_transport = newPk_transport;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "ehpta_transport";

	}
}
