  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.hi.hi_306;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2007-3-7
 * @author author
 * @version Your Project 1.0
 */
     public class DocApplyBVO extends SuperVO {
           
             public String pk_docapply_b;
             public String pk_docapply_h;
             public String pk_psndoc;
             public UFBoolean bapprove;
             public String def1;
             public String def2;
             public String def3;
             public String def4;
             public String def5;
             public String psncode;
             public String psnname;
                         
                	         
             public static final String  PK_DOCAPPLY_B="pk_docapply_b";   
             public static final String  PK_DOCAPPLY_H="pk_docapply_h";   
             public static final String  PK_PSNDOC="pk_psndoc";   
             public static final String  BAPPROVE="bapprove";   
             public static final String  PSNCODE="psncode";
             public static final String  PSNNAME="psnname";
             public static final String  DEF1="def1";
             public static final String  DEF2="def2";
             public static final String  DEF3="def3";
             public static final String  DEF4="def4";
             public static final String  DEF5="def5";
             
             public static final String TABLENAME = "hi_docapply_b";
             
             
            
            /**
			 * @return the def1
			 */
			public String getDef1() {
				return def1;
			}


			/**
			 * @param def1 the def1 to set
			 */
			public void setDef1(String def1) {
				this.def1 = def1;
			}


			/**
			 * @return the def2
			 */
			public String getDef2() {
				return def2;
			}


			/**
			 * @param def2 the def2 to set
			 */
			public void setDef2(String def2) {
				this.def2 = def2;
			}


			/**
			 * @return the def3
			 */
			public String getDef3() {
				return def3;
			}


			/**
			 * @param def3 the def3 to set
			 */
			public void setDef3(String def3) {
				this.def3 = def3;
			}


			/**
			 * @return the def4
			 */
			public String getDef4() {
				return def4;
			}


			/**
			 * @param def4 the def4 to set
			 */
			public void setDef4(String def4) {
				this.def4 = def4;
			}


			/**
			 * @return the def5
			 */
			public String getDef5() {
				return def5;
			}


			/**
			 * @param def5 the def5 to set
			 */
			public void setDef5(String def5) {
				this.def5 = def5;
			}


			/**
			 * @return the psncode
			 */
			public String getPsncode() {
				return psncode;
			}


			/**
			 * @param psncode the psncode to set
			 */
			public void setPsncode(String psncode) {
				this.psncode = psncode;
			}


			/**
			 * @return the psnname
			 */
			public String getPsnname() {
				return psnname;
			}


			/**
			 * @param psnname the psnname to set
			 */
			public void setPsnname(String psnname) {
				this.psnname = psnname;
			}


			public UFBoolean getBapprove() {
				return bapprove;
			}


			public void setBapprove(UFBoolean bapprove) {
				this.bapprove = bapprove;
			}


			public String getPk_docapply_b() {
				return pk_docapply_b;
			}


			public void setPk_docapply_b(String pk_docapply_b) {
				this.pk_docapply_b = pk_docapply_b;
			}


			public String getPk_docapply_h() {
				return pk_docapply_h;
			}


			public void setPk_docapply_h(String pk_docapply_h) {
				this.pk_docapply_h = pk_docapply_h;
			}


			public String getPk_psndoc() {
				return pk_psndoc;
			}


			public void setPk_psndoc(String pk_psndoc) {
				this.pk_psndoc = pk_psndoc;
			}



	/**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2007-3-7
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_docapply_b == null) {
			errFields.add(new String("pk_docapply_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
//		message.append("下列字段不能为空:");
	    message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID(
				"600700", "UPP600700-000346")/* @res "下列字段不能为空：" */);
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2007-3-7
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_docapply_h";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2007-3-7
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_docapply_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2007-3-7
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "hi_docapply_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2007-3-7
	  */
	public DocApplyBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2007-3-7
	 * @param newPk_docapply_b 主键值
	 */
	 public DocApplyBVO(String newPk_docapply_b) {
		
		// 为主键字段赋值:
		 pk_docapply_b = newPk_docapply_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2007-3-7
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_docapply_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2007-3-7
	  * @param newPk_docapply_b  String    
	  */
	 public void setPrimaryKey(String newPk_docapply_b) {
				
		 pk_docapply_b = newPk_docapply_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2007-3-7
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "hi_docapply_b"; 
				
	 }

	
} 
