  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ehpta.hq010901;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2012-8-7
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class CalcInterestVO extends SuperVO {
           
             public String vbillno;
             public UFDouble remny;
             public String contno;
             public String billtype;
             public String interestto;
             public String pk_receivable;
             public String custname;
             public String pk_calcinterest;
             public String transtype;
             public UFDate redate;
             public Integer version;
            
             public static final String  VBILLNO="vbillno";   
             public static final String  REMNY="remny";   
             public static final String  CONTNO="contno";   
             public static final String  BILLTYPE="billtype";   
             public static final String  INTERESTTO="interestto";   
             public static final String  PK_RECEIVABLE="pk_receivable";   
             public static final String  CUSTNAME="custname";   
             public static final String  PK_CALCINTEREST="pk_calcinterest";   
             public static final String  TRANSTYPE="transtype";   
             public static final String  REDATE="redate";   
             public static final String  VERSION="version";   
      
    
        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }   
	  
     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {
		
		vbillno = newVbillno;
	 } 	  
       
        /**
	   * 属性remny的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return UFDouble
	   */
	 public UFDouble getRemny() {
		 return remny;
	  }   
	  
     /**
	   * 属性remny的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newRemny UFDouble
	   */
	public void setRemny(UFDouble newRemny) {
		
		remny = newRemny;
	 } 	  
       
        /**
	   * 属性contno的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getContno() {
		 return contno;
	  }   
	  
     /**
	   * 属性contno的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newContno String
	   */
	public void setContno(String newContno) {
		
		contno = newContno;
	 } 	  
       
        /**
	   * 属性billtype的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getBilltype() {
		 return billtype;
	  }   
	  
     /**
	   * 属性billtype的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newBilltype String
	   */
	public void setBilltype(String newBilltype) {
		
		billtype = newBilltype;
	 } 	  
       
        /**
	   * 属性interestto的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getInterestto() {
		 return interestto;
	  }   
	  
     /**
	   * 属性interestto的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newInterestto String
	   */
	public void setInterestto(String newInterestto) {
		
		interestto = newInterestto;
	 } 	  
       
        /**
	   * 属性pk_receivable的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getPk_receivable() {
		 return pk_receivable;
	  }   
	  
     /**
	   * 属性pk_receivable的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newPk_receivable String
	   */
	public void setPk_receivable(String newPk_receivable) {
		
		pk_receivable = newPk_receivable;
	 } 	  
       
        /**
	   * 属性custname的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getCustname() {
		 return custname;
	  }   
	  
     /**
	   * 属性custname的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newCustname String
	   */
	public void setCustname(String newCustname) {
		
		custname = newCustname;
	 } 	  
       
        /**
	   * 属性pk_calcinterest的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getPk_calcinterest() {
		 return pk_calcinterest;
	  }   
	  
     /**
	   * 属性pk_calcinterest的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newPk_calcinterest String
	   */
	public void setPk_calcinterest(String newPk_calcinterest) {
		
		pk_calcinterest = newPk_calcinterest;
	 } 	  
       
        /**
	   * 属性transtype的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return String
	   */
	 public String getTranstype() {
		 return transtype;
	  }   
	  
     /**
	   * 属性transtype的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newTranstype String
	   */
	public void setTranstype(String newTranstype) {
		
		transtype = newTranstype;
	 } 	  
       
        /**
	   * 属性redate的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return UFDate
	   */
	 public UFDate getRedate() {
		 return redate;
	  }   
	  
     /**
	   * 属性redate的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newRedate UFDate
	   */
	public void setRedate(UFDate newRedate) {
		
		redate = newRedate;
	 } 	  
       
        /**
	   * 属性version的Getter方法.
	   *
	   * 创建日期:2012-8-7
	   * @return Integer
	   */
	 public Integer getVersion() {
		 return version;
	  }   
	  
     /**
	   * 属性version的Setter方法.
	   *
	   * 创建日期:2012-8-7
	   * @param newVersion Integer
	   */
	public void setVersion(Integer newVersion) {
		
		version = newVersion;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2012-8-7
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_calcinterest == null) {
			errFields.add(new String("pk_calcinterest"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-8-7
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-8-7
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_calcinterest";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2012-8-7
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ehpta_calc_interest";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-8-7
	  */
	public CalcInterestVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2012-8-7
	 * @param newPk_calcinterest 主键值
	 */
	 public CalcInterestVO(String newPk_calcinterest) {
		
		// 为主键字段赋值:
		 pk_calcinterest = newPk_calcinterest;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-8-7
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_calcinterest;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-8-7
	  * @param newPk_calcinterest  String    
	  */
	 public void setPrimaryKey(String newPk_calcinterest) {
				
				pk_calcinterest = newPk_calcinterest; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2012-8-7
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ehpta_calc_interest"; 
				
	 } 
} 
