/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.eh.iso.z0502005;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2008-4-14
 * 
 * @author author
 * @version Your Project 1.0
 */
public class StockCheckreportBVO extends SuperVO {

	public String pk_corp;
    //收货指标下限	
	public UFDouble rece_limit;
	public String def_3;
	public String def_1;
	public Integer dr;
    //收货指标上限	
	public UFDouble rece_ceil;
	public String pk_project;
	public UFDouble def_9;
	public UFDouble def_10;
	public Integer itemno;
	public String def_2;
	public UFDouble def_8;
	public String vsourcebilltype;
	public UFDateTime ts;
	public String vsourcebillrowid;
	public String pk_checkreport_b;
	public String pk_checkreport;
	public String memo;
	public UFDouble def_6;
	public String pk_iso;
	public UFDouble checkresult;
	public String def_5;
	public UFBoolean pass_flag;
    //理论指标下限  	
	public UFDouble ll_limit;
    //理论指标上限 	
	public UFDouble ll_ceil;
	public String rowidd;
	public String def_4;
	public UFDouble def_7;
	public String vsourcebillid;
	public String pk_sample;
	public String fxtype;
	public UFDouble def_11;
	public UFDouble def_12;
	public UFDouble def_13;
	public UFDouble def_14;
	public UFDouble def_15;
	public Integer result;
	public UFDouble kzkj; // 扣重扣价
	public UFDouble invprice; // 价格
	public Integer iskzkj; // 是否扣重扣价
	public Integer groupitem; // 项目分组
	public Integer ishigh;

	public static final String FXTYPE = "fxtype";
	public static final String ISHIGH = "ishigh";
	public static final String GROUPITEM = "groupitem";
	public static final String INVPRICE = "invprice";
	public static final String KZKJ = "kzkj";
	public static final String DEF_11 = "def_11";
	public static final String DEF_12 = "def_12";
	public static final String DEF_13 = "def_13";
	public static final String DEF_14 = "def_14";
	public static final String DEF_15 = "def_15";
	public static final String PK_CORP = "pk_corp";
	public static final String RECE_LIMIT = "rece_limit";
	public static final String DEF_3 = "def_3";
	public static final String DEF_1 = "def_1";
	public static final String DR = "dr";
	public static final String RECE_CEIL = "rece_ceil";
	public static final String PK_PROJECT = "pk_project";
	public static final String DEF_9 = "def_9";
	public static final String DEF_10 = "def_10";
	public static final String ITEMNO = "itemno";
	public static final String DEF_2 = "def_2";
	public static final String DEF_8 = "def_8";
	public static final String VSOURCEBILLTYPE = "vsourcebilltype";
	public static final String TS = "ts";
	public static final String VSOURCEBILLROWID = "vsourcebillrowid";
	public static final String PK_CHECKREPORT_B = "pk_checkreport_b";
	public static final String PK_CHECKREPORT = "pk_checkreport";
	public static final String MEMO = "memo";
	public static final String DEF_6 = "def_6";
	public static final String PK_ISO = "pk_iso";
	public static final String CHECKRESULT = "checkresult";
	public static final String DEF_5 = "def_5";
	public static final String PASS_FLAG = "pass_flag";
	public static final String LL_LIMIT = "ll_limit";
	public static final String LL_CEIL = "ll_ceil";
	public static final String ROWID = "rowid";
	public static final String DEF_4 = "def_4";
	public static final String DEF_7 = "def_7";
	public static final String VSOURCEBILLID = "vsourcebillid";
	public static final String PK_SAMPLE = "pk_sample";

	/**
	 * @return the result
	 */
	public Integer getResult() {
		return result;
	}

	/**
	 * @param result
	 *            the result to set
	 */
	public void setResult(Integer result) {
		this.result = result;
	}

	public String getFxtype() {
		return fxtype;
	}

	public void setFxtype(String fxtype) {
		this.fxtype = fxtype;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性rece_limit的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public UFDouble getRece_limit() {
		return rece_limit;
	}

	/**
	 * 属性rece_limit的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newRece_limit
	 *            String
	 */
	public void setRece_limit(UFDouble newRece_limit) {

		rece_limit = newRece_limit;
	}

	/**
	 * 属性def_3的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getDef_3() {
		return def_3;
	}

	/**
	 * 属性def_3的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_3
	 *            String
	 */
	public void setDef_3(String newDef_3) {

		def_3 = newDef_3;
	}

	/**
	 * 属性def_1的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getDef_1() {
		return def_1;
	}

	/**
	 * 属性def_1的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_1
	 *            String
	 */
	public void setDef_1(String newDef_1) {

		def_1 = newDef_1;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性rece_ceil的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public UFDouble getRece_ceil() {
		return rece_ceil;
	}

	/**
	 * 属性rece_ceil的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newRece_ceil
	 *            String
	 */
	public void setRece_ceil(UFDouble newRece_ceil) {

		rece_ceil = newRece_ceil;
	}

	/**
	 * 属性pk_project的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPk_project() {
		return pk_project;
	}

	/**
	 * 属性pk_project的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_project
	 *            String
	 */
	public void setPk_project(String newPk_project) {

		pk_project = newPk_project;
	}

	/**
	 * 属性def_9的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return UFDouble
	 */
	public UFDouble getDef_9() {
		return def_9;
	}

	/**
	 * 属性def_9的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_9
	 *            UFDouble
	 */
	public void setDef_9(UFDouble newDef_9) {

		def_9 = newDef_9;
	}

	/**
	 * 属性def_10的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return UFDouble
	 */
	public UFDouble getDef_10() {
		return def_10;
	}

	/**
	 * 属性def_10的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_10
	 *            UFDouble
	 */
	public void setDef_10(UFDouble newDef_10) {

		def_10 = newDef_10;
	}

	/**
	 * 属性itemno的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return Integer
	 */
	public Integer getItemno() {
		return itemno;
	}

	/**
	 * 属性itemno的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newItemno
	 *            Integer
	 */
	public void setItemno(Integer newItemno) {

		itemno = newItemno;
	}

	/**
	 * 属性def_2的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getDef_2() {
		return def_2;
	}

	/**
	 * 属性def_2的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_2
	 *            String
	 */
	public void setDef_2(String newDef_2) {

		def_2 = newDef_2;
	}

	/**
	 * 属性def_8的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return UFDouble
	 */
	public UFDouble getDef_8() {
		return def_8;
	}

	/**
	 * 属性def_8的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_8
	 *            UFDouble
	 */
	public void setDef_8(UFDouble newDef_8) {

		def_8 = newDef_8;
	}

	/**
	 * 属性vsourcebilltype的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getVsourcebilltype() {
		return vsourcebilltype;
	}

	/**
	 * 属性vsourcebilltype的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newVsourcebilltype
	 *            String
	 */
	public void setVsourcebilltype(String newVsourcebilltype) {

		vsourcebilltype = newVsourcebilltype;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	/**
	 * 属性vsourcebillrowid的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getVsourcebillrowid() {
		return vsourcebillrowid;
	}

	/**
	 * 属性vsourcebillrowid的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newVsourcebillrowid
	 *            String
	 */
	public void setVsourcebillrowid(String newVsourcebillrowid) {

		vsourcebillrowid = newVsourcebillrowid;
	}

	/**
	 * 属性pk_checkreport_b的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPk_checkreport_b() {
		return pk_checkreport_b;
	}

	/**
	 * 属性pk_checkreport_b的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_checkreport_b
	 *            String
	 */
	public void setPk_checkreport_b(String newPk_checkreport_b) {

		pk_checkreport_b = newPk_checkreport_b;
	}

	/**
	 * 属性pk_checkreport的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPk_checkreport() {
		return pk_checkreport;
	}

	/**
	 * 属性pk_checkreport的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_checkreport
	 *            String
	 */
	public void setPk_checkreport(String newPk_checkreport) {

		pk_checkreport = newPk_checkreport;
	}

	/**
	 * 属性memo的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * 属性memo的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {

		memo = newMemo;
	}

	/**
	 * 属性def_6的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return UFDouble
	 */
	public UFDouble getDef_6() {
		return def_6;
	}

	/**
	 * 属性def_6的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_6
	 *            UFDouble
	 */
	public void setDef_6(UFDouble newDef_6) {

		def_6 = newDef_6;
	}

	/**
	 * 属性pk_iso的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPk_iso() {
		return pk_iso;
	}

	/**
	 * 属性pk_iso的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_iso
	 *            String
	 */
	public void setPk_iso(String newPk_iso) {

		pk_iso = newPk_iso;
	}

	/**
	 * 属性checkresult的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public UFDouble getCheckresult() {
		return checkresult;
	}

	/**
	 * 属性checkresult的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newCheckresult
	 *            String
	 */
	public void setCheckresult(UFDouble newCheckresult) {

		checkresult = newCheckresult;
	}

	/**
	 * 属性def_5的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getDef_5() {
		return def_5;
	}

	/**
	 * 属性def_5的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_5
	 *            String
	 */
	public void setDef_5(String newDef_5) {

		def_5 = newDef_5;
	}

	/**
	 * 属性pass_flag的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public UFBoolean getPass_flag() {
		return pass_flag;
	}

	/**
	 * 属性pass_flag的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPass_flag
	 *            String
	 */
	public void setPass_flag(UFBoolean newPass_flag) {

		pass_flag = newPass_flag;
	}

	/**
	 * 属性ll_limit的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public UFDouble getLl_limit() {
		return ll_limit;
	}

	/**
	 * 属性ll_limit的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newLl_limit
	 *            String
	 */
	public void setLl_limit(UFDouble newLl_limit) {

		ll_limit = newLl_limit;
	}

	/**
	 * 属性ll_ceil的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public UFDouble getLl_ceil() {
		return ll_ceil;
	}

	/**
	 * 属性ll_ceil的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newLl_ceil
	 *            String
	 */
	public void setLl_ceil(UFDouble newLl_ceil) {

		ll_ceil = newLl_ceil;
	}

	public String getRowidd() {
		return rowidd;
	}

	public void setRowidd(String rowidd) {
		this.rowidd = rowidd;
	}

	/**
	 * 属性def_4的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getDef_4() {
		return def_4;
	}

	/**
	 * 属性def_4的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_4
	 *            String
	 */
	public void setDef_4(String newDef_4) {

		def_4 = newDef_4;
	}

	/**
	 * 属性def_7的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return UFDouble
	 */
	public UFDouble getDef_7() {
		return def_7;
	}

	/**
	 * 属性def_7的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newDef_7
	 *            UFDouble
	 */
	public void setDef_7(UFDouble newDef_7) {

		def_7 = newDef_7;
	}

	/**
	 * 属性vsourcebillid的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getVsourcebillid() {
		return vsourcebillid;
	}

	/**
	 * 属性vsourcebillid的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newVsourcebillid
	 *            String
	 */
	public void setVsourcebillid(String newVsourcebillid) {

		vsourcebillid = newVsourcebillid;
	}

	/**
	 * 属性pk_sample的Getter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPk_sample() {
		return pk_sample;
	}

	/**
	 * 属性pk_sample的Setter方法.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_sample
	 *            String
	 */
	public void setPk_sample(String newPk_sample) {

		pk_sample = newPk_sample;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2008-4-14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "pk_checkreport";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2008-4-14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_checkreport_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2008-4-14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "eh_stock_checkreport_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2008-4-14
	 */
	public StockCheckreportBVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_checkreport_b
	 *            主键值
	 */
	public StockCheckreportBVO(String newPk_checkreport_b) {

		// 为主键字段赋值:
		pk_checkreport_b = newPk_checkreport_b;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_checkreport_b;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @param newPk_checkreport_b
	 *            String
	 */
	public void setPrimaryKey(String newPk_checkreport_b) {

		pk_checkreport_b = newPk_checkreport_b;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2008-4-14
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "eh_stock_checkreport_b";

	}

	public UFDouble getDef_11() {
		return def_11;
	}

	public void setDef_11(UFDouble def_11) {
		this.def_11 = def_11;
	}

	public UFDouble getDef_12() {
		return def_12;
	}

	public void setDef_12(UFDouble def_12) {
		this.def_12 = def_12;
	}

	public UFDouble getDef_13() {
		return def_13;
	}

	public void setDef_13(UFDouble def_13) {
		this.def_13 = def_13;
	}

	public UFDouble getDef_14() {
		return def_14;
	}

	public void setDef_14(UFDouble def_14) {
		this.def_14 = def_14;
	}

	public UFDouble getDef_15() {
		return def_15;
	}

	public void setDef_15(UFDouble def_15) {
		this.def_15 = def_15;
	}

	public UFDouble getKzkj() {
		return kzkj;
	}

	public void setKzkj(UFDouble kzkj) {
		this.kzkj = kzkj;
	}

	public UFDouble getInvprice() {
		return invprice;
	}

	public void setInvprice(UFDouble invprice) {
		this.invprice = invprice;
	}

	public Integer getIskzkj() {
		return iskzkj;
	}

	public void setIskzkj(Integer iskzkj) {
		this.iskzkj = iskzkj;
	}

	public Integer getGroupitem() {
		return groupitem;
	}

	public void setGroupitem(Integer groupitem) {
		this.groupitem = groupitem;
	}

	public Integer getIshigh() {
		return ishigh;
	}

	public void setIshigh(Integer ishigh) {
		this.ishigh = ishigh;
	}
}
