  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ehpta.hq010401;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2012-7-9
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class SaleContractBsVO extends SuperVO {
           
             public String def5;
             public Integer dr;
             public String def7;
             public String pk_invbasdoc;
             public UFDateTime ts;
             public String def6;
             public UFDouble sumpricetax;
             public String pk_contract;
             public String def10;
             public String pk_measdoc;
             public String memo;
             public UFDouble taxrate;
             public String def8;
             public String invname;
             public String def1;
             public UFDouble taxprice;
             public UFDouble num;
             public String def2;
             public Integer numof;
             public UFDouble notaxloan;
             public UFDouble tax;
             public String def4;
             public String def3;
             public String def9;
             public String invspec;
             public String pk_contract_b;
            
             public static final String  DEF5="def5";   
             public static final String  DR="dr";   
             public static final String  DEF7="def7";   
             public static final String  PK_INVBASDOC="pk_invbasdoc";   
             public static final String  TS="ts";   
             public static final String  DEF6="def6";   
             public static final String  SUMPRICETAX="sumpricetax";   
             public static final String  PK_CONTRACT="pk_contract";   
             public static final String  DEF10="def10";   
             public static final String  PK_MEASDOC="pk_measdoc";   
             public static final String  MEMO="memo";   
             public static final String  TAXRATE="taxrate";   
             public static final String  DEF8="def8";   
             public static final String  INVNAME="invname";   
             public static final String  DEF1="def1";   
             public static final String  TAXPRICE="taxprice";   
             public static final String  NUM="num";   
             public static final String  DEF2="def2";   
             public static final String  NUMOF="numof";   
             public static final String  NOTAXLOAN="notaxloan";   
             public static final String  TAX="tax";   
             public static final String  DEF4="def4";   
             public static final String  DEF3="def3";   
             public static final String  DEF9="def9";   
             public static final String  INVSPEC="invspec";   
             public static final String  PK_CONTRACT_B="pk_contract_b";   
      
    
        /**
	   * 属性def5的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef5() {
		 return def5;
	  }   
	  
     /**
	   * 属性def5的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef5 String
	   */
	public void setDef5(String newDef5) {
		
		def5 = newDef5;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性def7的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef7() {
		 return def7;
	  }   
	  
     /**
	   * 属性def7的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef7 String
	   */
	public void setDef7(String newDef7) {
		
		def7 = newDef7;
	 } 	  
       
        /**
	   * 属性pk_invbasdoc的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getPk_invbasdoc() {
		 return pk_invbasdoc;
	  }   
	  
     /**
	   * 属性pk_invbasdoc的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newPk_invbasdoc String
	   */
	public void setPk_invbasdoc(String newPk_invbasdoc) {
		
		pk_invbasdoc = newPk_invbasdoc;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性def6的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef6() {
		 return def6;
	  }   
	  
     /**
	   * 属性def6的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef6 String
	   */
	public void setDef6(String newDef6) {
		
		def6 = newDef6;
	 } 	  
       
        /**
	   * 属性sumpricetax的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public UFDouble getSumpricetax() {
		 return sumpricetax;
	  }   
	  
     /**
	   * 属性sumpricetax的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newSumpricetax UFDouble
	   */
	public void setSumpricetax(UFDouble newSumpricetax) {
		
		sumpricetax = newSumpricetax;
	 } 	  
       
        /**
	   * 属性pk_contract的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getPk_contract() {
		 return pk_contract;
	  }   
	  
     /**
	   * 属性pk_contract的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newPk_contract String
	   */
	public void setPk_contract(String newPk_contract) {
		
		pk_contract = newPk_contract;
	 } 	  
       
        /**
	   * 属性def10的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef10() {
		 return def10;
	  }   
	  
     /**
	   * 属性def10的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef10 String
	   */
	public void setDef10(String newDef10) {
		
		def10 = newDef10;
	 } 	  
       
        /**
	   * 属性pk_measdoc的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getPk_measdoc() {
		 return pk_measdoc;
	  }   
	  
     /**
	   * 属性pk_measdoc的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newPk_measdoc String
	   */
	public void setPk_measdoc(String newPk_measdoc) {
		
		pk_measdoc = newPk_measdoc;
	 } 	  
       
        /**
	   * 属性memo的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getMemo() {
		 return memo;
	  }   
	  
     /**
	   * 属性memo的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newMemo String
	   */
	public void setMemo(String newMemo) {
		
		memo = newMemo;
	 } 	  
       
        /**
	   * 属性taxrate的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public UFDouble getTaxrate() {
		 return taxrate;
	  }   
	  
     /**
	   * 属性taxrate的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newTaxrate UFDouble
	   */
	public void setTaxrate(UFDouble newTaxrate) {
		
		taxrate = newTaxrate;
	 } 	  
       
        /**
	   * 属性def8的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef8() {
		 return def8;
	  }   
	  
     /**
	   * 属性def8的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef8 String
	   */
	public void setDef8(String newDef8) {
		
		def8 = newDef8;
	 } 	  
       
        /**
	   * 属性invname的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getInvname() {
		 return invname;
	  }   
	  
     /**
	   * 属性invname的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newInvname String
	   */
	public void setInvname(String newInvname) {
		
		invname = newInvname;
	 } 	  
       
        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef1() {
		 return def1;
	  }   
	  
     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef1 String
	   */
	public void setDef1(String newDef1) {
		
		def1 = newDef1;
	 } 	  
       
        /**
	   * 属性taxprice的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public UFDouble getTaxprice() {
		 return taxprice;
	  }   
	  
     /**
	   * 属性taxprice的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newTaxprice UFDouble
	   */
	public void setTaxprice(UFDouble newTaxprice) {
		
		taxprice = newTaxprice;
	 } 	  
       
        /**
	   * 属性num的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public UFDouble getNum() {
		 return num;
	  }   
	  
     /**
	   * 属性num的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newNum UFDouble
	   */
	public void setNum(UFDouble newNum) {
		
		num = newNum;
	 } 	  
       
        /**
	   * 属性def2的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef2() {
		 return def2;
	  }   
	  
     /**
	   * 属性def2的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef2 String
	   */
	public void setDef2(String newDef2) {
		
		def2 = newDef2;
	 } 	  
       
        /**
	   * 属性numof的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public Integer getNumof() {
		 return numof;
	  }   
	  
     /**
	   * 属性numof的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newNumof UFDouble
	   */
	public void setNumof(Integer newNumof) {
		
		numof = newNumof;
	 } 	  
       
        /**
	   * 属性notaxloan的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public UFDouble getNotaxloan() {
		 return notaxloan;
	  }   
	  
     /**
	   * 属性notaxloan的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newNotaxloan UFDouble
	   */
	public void setNotaxloan(UFDouble newNotaxloan) {
		
		notaxloan = newNotaxloan;
	 } 	  
       
        /**
	   * 属性tax的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return UFDouble
	   */
	 public UFDouble getTax() {
		 return tax;
	  }   
	  
     /**
	   * 属性tax的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newTax UFDouble
	   */
	public void setTax(UFDouble newTax) {
		
		tax = newTax;
	 } 	  
       
        /**
	   * 属性def4的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef4() {
		 return def4;
	  }   
	  
     /**
	   * 属性def4的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef4 String
	   */
	public void setDef4(String newDef4) {
		
		def4 = newDef4;
	 } 	  
       
        /**
	   * 属性def3的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef3() {
		 return def3;
	  }   
	  
     /**
	   * 属性def3的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef3 String
	   */
	public void setDef3(String newDef3) {
		
		def3 = newDef3;
	 } 	  
       
        /**
	   * 属性def9的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getDef9() {
		 return def9;
	  }   
	  
     /**
	   * 属性def9的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newDef9 String
	   */
	public void setDef9(String newDef9) {
		
		def9 = newDef9;
	 } 	  
       
        /**
	   * 属性invspec的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getInvspec() {
		 return invspec;
	  }   
	  
     /**
	   * 属性invspec的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newInvspec String
	   */
	public void setInvspec(String newInvspec) {
		
		invspec = newInvspec;
	 } 	  
       
        /**
	   * 属性pk_contract_b的Getter方法.
	   *
	   * 创建日期:2012-7-9
	   * @return String
	   */
	 public String getPk_contract_b() {
		 return pk_contract_b;
	  }   
	  
     /**
	   * 属性pk_contract_b的Setter方法.
	   *
	   * 创建日期:2012-7-9
	   * @param newPk_contract_b String
	   */
	public void setPk_contract_b(String newPk_contract_b) {
		
		pk_contract_b = newPk_contract_b;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2012-7-9
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_contract_b == null) {
			errFields.add(new String("pk_contract_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-7-9
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_contract";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-7-9
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_contract_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2012-7-9
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ehpta_sale_contract_bs";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-7-9
	  */
	public SaleContractBsVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2012-7-9
	 * @param newPk_contract_b 主键值
	 */
	 public SaleContractBsVO(String newPk_contract_b) {
		
		// 为主键字段赋值:
		 pk_contract_b = newPk_contract_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-7-9
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_contract_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-7-9
	  * @param newPk_contract_b  String    
	  */
	 public void setPrimaryKey(String newPk_contract_b) {
				
				pk_contract_b = newPk_contract_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2012-7-9
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ehpta_sale_contract_bs"; 
				
	 } 
} 
