package nc.itf.tc.imp;


/**
 * This class was generated by NC WS Tools.
 * Fri Mar 11 13:44:56 CST 2011
 * Generated source version: v1299822296968
 * 
 */


public interface IQueryList {

    public String importXSLRep(String string,String string1,String string2,String string3,String string4);

    public String testText(String string);

}
