  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ehpta.hq010901;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2012-8-20
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class CalcInterestBVO extends SuperVO {
           
             public Integer days;
             public String def5;
             public String billtype;
             public UFBoolean calcflag;
             public Integer dr;
             public String custname;
             public String pk_receivable;
             public String transtype;
             public String def7;
             public String djzbid;
             public String def6;
             public String ts;
             public String interestto;
             public String pk_calcinterest;
             public UFDouble interestmny;
             public UFDouble rate;
             public String def10;
             public String memo;
             public UFDouble remny;
             public String def8;
             public String def1;
             public String version;
             public UFDouble actualmny;
             public String def2;
             public String contno;
             public String pk_calcinterest_b;
             public String def4;
             public String def3;
             public String def9;
             public UFDate redate;
            
             public static final String  DAYS="days";   
             public static final String  DEF5="def5";   
             public static final String  BILLTYPE="billtype";   
             public static final String  CALCFLAG="calcflag";   
             public static final String  DR="dr";   
             public static final String  CUSTNAME="custname";   
             public static final String  PK_RECEIVABLE="pk_receivable";   
             public static final String  TRANSTYPE="transtype";   
             public static final String  DEF7="def7";   
             public static final String  DJZBID="djzbid";   
             public static final String  DEF6="def6";   
             public static final String  TS="ts";   
             public static final String  INTERESTTO="interestto";   
             public static final String  PK_CALCINTEREST="pk_calcinterest";   
             public static final String  INTERESTMNY="interestmny";   
             public static final String  RATE="rate";   
             public static final String  DEF10="def10";   
             public static final String  MEMO="memo";   
             public static final String  REMNY="remny";   
             public static final String  DEF8="def8";   
             public static final String  DEF1="def1";   
             public static final String  VERSION="version";   
             public static final String  ACTUALMNY="actualmny";   
             public static final String  DEF2="def2";   
             public static final String  CONTNO="contno";   
             public static final String  PK_CALCINTEREST_B="pk_calcinterest_b";   
             public static final String  DEF4="def4";   
             public static final String  DEF3="def3";   
             public static final String  DEF9="def9";   
             public static final String  REDATE="redate";   
      
    
        /**
	   * 属性days的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return Integer
	   */
	 public Integer getDays() {
		 return days;
	  }   
	  
     /**
	   * 属性days的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDays Integer
	   */
	public void setDays(Integer newDays) {
		
		days = newDays;
	 } 	  
       
        /**
	   * 属性def5的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef5() {
		 return def5;
	  }   
	  
     /**
	   * 属性def5的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef5 String
	   */
	public void setDef5(String newDef5) {
		
		def5 = newDef5;
	 } 	  
       
        /**
	   * 属性billtype的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getBilltype() {
		 return billtype;
	  }   
	  
     /**
	   * 属性billtype的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newBilltype String
	   */
	public void setBilltype(String newBilltype) {
		
		billtype = newBilltype;
	 } 	  
       
        /**
	   * 属性calcflag的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFBoolean
	   */
	 public UFBoolean getCalcflag() {
		 return calcflag;
	  }   
	  
     /**
	   * 属性calcflag的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newCalcflag UFBoolean
	   */
	public void setCalcflag(UFBoolean newCalcflag) {
		
		calcflag = newCalcflag;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性custname的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getCustname() {
		 return custname;
	  }   
	  
     /**
	   * 属性custname的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newCustname String
	   */
	public void setCustname(String newCustname) {
		
		custname = newCustname;
	 } 	  
       
        /**
	   * 属性pk_receivable的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getPk_receivable() {
		 return pk_receivable;
	  }   
	  
     /**
	   * 属性pk_receivable的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newPk_receivable String
	   */
	public void setPk_receivable(String newPk_receivable) {
		
		pk_receivable = newPk_receivable;
	 } 	  
       
        /**
	   * 属性transtype的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getTranstype() {
		 return transtype;
	  }   
	  
     /**
	   * 属性transtype的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newTranstype String
	   */
	public void setTranstype(String newTranstype) {
		
		transtype = newTranstype;
	 } 	  
       
        /**
	   * 属性def7的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef7() {
		 return def7;
	  }   
	  
     /**
	   * 属性def7的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef7 String
	   */
	public void setDef7(String newDef7) {
		
		def7 = newDef7;
	 } 	  
       
        /**
	   * 属性djzbid的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDjzbid() {
		 return djzbid;
	  }   
	  
     /**
	   * 属性djzbid的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDjzbid String
	   */
	public void setDjzbid(String newDjzbid) {
		
		djzbid = newDjzbid;
	 } 	  
       
        /**
	   * 属性def6的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef6() {
		 return def6;
	  }   
	  
     /**
	   * 属性def6的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef6 String
	   */
	public void setDef6(String newDef6) {
		
		def6 = newDef6;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFDateTime
	   */
	 public String getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性interestto的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getInterestto() {
		 return interestto;
	  }   
	  
     /**
	   * 属性interestto的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newInterestto String
	   */
	public void setInterestto(String newInterestto) {
		
		interestto = newInterestto;
	 } 	  
       
        /**
	   * 属性pk_calcinterest的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getPk_calcinterest() {
		 return pk_calcinterest;
	  }   
	  
     /**
	   * 属性pk_calcinterest的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newPk_calcinterest String
	   */
	public void setPk_calcinterest(String newPk_calcinterest) {
		
		pk_calcinterest = newPk_calcinterest;
	 } 	  
       
        /**
	   * 属性interestmny的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFDouble
	   */
	 public UFDouble getInterestmny() {
		 return interestmny;
	  }   
	  
     /**
	   * 属性interestmny的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newInterestmny UFDouble
	   */
	public void setInterestmny(UFDouble newInterestmny) {
		
		interestmny = newInterestmny;
	 } 	  
       
        /**
	   * 属性rate的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFDouble
	   */
	 public UFDouble getRate() {
		 return rate;
	  }   
	  
     /**
	   * 属性rate的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newRate UFDouble
	   */
	public void setRate(UFDouble newRate) {
		
		rate = newRate;
	 } 	  
       
        /**
	   * 属性def10的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef10() {
		 return def10;
	  }   
	  
     /**
	   * 属性def10的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef10 String
	   */
	public void setDef10(String newDef10) {
		
		def10 = newDef10;
	 } 	  
       
        /**
	   * 属性memo的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getMemo() {
		 return memo;
	  }   
	  
     /**
	   * 属性memo的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newMemo String
	   */
	public void setMemo(String newMemo) {
		
		memo = newMemo;
	 } 	  
       
        /**
	   * 属性remny的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFDouble
	   */
	 public UFDouble getRemny() {
		 return remny;
	  }   
	  
     /**
	   * 属性remny的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newRemny UFDouble
	   */
	public void setRemny(UFDouble newRemny) {
		
		remny = newRemny;
	 } 	  
       
        /**
	   * 属性def8的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef8() {
		 return def8;
	  }   
	  
     /**
	   * 属性def8的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef8 String
	   */
	public void setDef8(String newDef8) {
		
		def8 = newDef8;
	 } 	  
       
        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef1() {
		 return def1;
	  }   
	  
     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef1 String
	   */
	public void setDef1(String newDef1) {
		
		def1 = newDef1;
	 } 	  
       
        /**
	   * 属性version的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getVersion() {
		 return version;
	  }   
	  
     /**
	   * 属性version的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newVersion String
	   */
	public void setVersion(String newVersion) {
		
		version = newVersion;
	 } 	  
       
        /**
	   * 属性actualmny的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFDouble
	   */
	 public UFDouble getActualmny() {
		 return actualmny;
	  }   
	  
     /**
	   * 属性actualmny的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newActualmny UFDouble
	   */
	public void setActualmny(UFDouble newActualmny) {
		
		actualmny = newActualmny;
	 } 	  
       
        /**
	   * 属性def2的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef2() {
		 return def2;
	  }   
	  
     /**
	   * 属性def2的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef2 String
	   */
	public void setDef2(String newDef2) {
		
		def2 = newDef2;
	 } 	  
       
        /**
	   * 属性contno的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getContno() {
		 return contno;
	  }   
	  
     /**
	   * 属性contno的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newContno String
	   */
	public void setContno(String newContno) {
		
		contno = newContno;
	 } 	  
       
        /**
	   * 属性pk_calcinterest_b的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getPk_calcinterest_b() {
		 return pk_calcinterest_b;
	  }   
	  
     /**
	   * 属性pk_calcinterest_b的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newPk_calcinterest_b String
	   */
	public void setPk_calcinterest_b(String newPk_calcinterest_b) {
		
		pk_calcinterest_b = newPk_calcinterest_b;
	 } 	  
       
        /**
	   * 属性def4的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef4() {
		 return def4;
	  }   
	  
     /**
	   * 属性def4的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef4 String
	   */
	public void setDef4(String newDef4) {
		
		def4 = newDef4;
	 } 	  
       
        /**
	   * 属性def3的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef3() {
		 return def3;
	  }   
	  
     /**
	   * 属性def3的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef3 String
	   */
	public void setDef3(String newDef3) {
		
		def3 = newDef3;
	 } 	  
       
        /**
	   * 属性def9的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return String
	   */
	 public String getDef9() {
		 return def9;
	  }   
	  
     /**
	   * 属性def9的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newDef9 String
	   */
	public void setDef9(String newDef9) {
		
		def9 = newDef9;
	 } 	  
       
        /**
	   * 属性redate的Getter方法.
	   *
	   * 创建日期:2012-8-20
	   * @return UFDate
	   */
	 public UFDate getRedate() {
		 return redate;
	  }   
	  
     /**
	   * 属性redate的Setter方法.
	   *
	   * 创建日期:2012-8-20
	   * @param newRedate UFDate
	   */
	public void setRedate(UFDate newRedate) {
		
		redate = newRedate;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2012-8-20
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_calcinterest_b == null) {
			errFields.add(new String("pk_calcinterest_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-8-20
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_calcinterest";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-8-20
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_calcinterest_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2012-8-20
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ehpta_calc_interest_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-8-20
	  */
	public CalcInterestBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2012-8-20
	 * @param newPk_calcinterest_b 主键值
	 */
	 public CalcInterestBVO(String newPk_calcinterest_b) {
		
		// 为主键字段赋值:
		 pk_calcinterest_b = newPk_calcinterest_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-8-20
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_calcinterest_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-8-20
	  * @param newPk_calcinterest_b  String    
	  */
	 public void setPrimaryKey(String newPk_calcinterest_b) {
				
				pk_calcinterest_b = newPk_calcinterest_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2012-8-20
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ehpta_calc_interest_b"; 
				
	 } 
} 
