prompt Importing table pub_query_condition...
set feedback off
set define off
insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.vbillno', '单据号', '0001AA1000000028KE3Q', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('<nc.ui.ehpta.pub.ref.PeriodRefPane>', 5, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.period', '期间', '0001AA1000000028KE3R', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 6, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.vbillstatus', '单据状态', '0001AA1000000028KE3S', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def1', '自定义字段1', '0001AA1000000028KE3T', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def2', '自定义字段2', '0001AA1000000028KE3U', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def3', '自定义字段3', '0001AA1000000028KE3V', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def4', '自定义字段4', '0001AA1000000028KE3W', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def5', '自定义字段5', '0001AA1000000028KE3X', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def6', '自定义字段6', '0001AA1000000028KE3Y', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def7', '自定义字段7', '0001AA1000000028KE3Z', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def8', '自定义字段8', '0001AA1000000028KE40', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def9', '自定义字段9', '0001AA1000000028KE41', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.def10', '自定义字段10', '0001AA1000000028KE42', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 1, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.dr', '删除标记', '0001AA1000000028KE43', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.pk_billtype', '单据类型', '0001AA1000000028KE44', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.pk_busitype', '业务类型', '0001AA1000000028KE45', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.pk_corp', '公司', '0001AA1000000028KE46', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.pk_sale_balance', '主键', '0001AA1000000028KE47', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.ts', '时间戳', '0001AA1000000028KE48', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.concode', '合同编码', '0001AA1000000028KE49', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.connamed', '纸质合同编号', '0001AA1000000028KE4A', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.custname', '客商名称', '0001AA1000000028KE4B', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.firstmny', '期初货款', '0001AA1000000028KE4C', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.currmny', '本期收入货款', '0001AA1000000028KE4D', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.salemny', '提单金额', '0001AA1000000028KE4E', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.salebalance', '货款余额', '0001AA1000000028KE4F', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.adtype2', '贴现额', '0001AA1000000028KE4G', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.adtype3', '挂结价差额', '0001AA1000000028KE4H', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.adtype4', '优惠返利额', '0001AA1000000028KE4I', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.balance', '总余额', '0001AA1000000028KE4J', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def1', '自定义项1', '0001AA1000000028KE4K', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def10', '自定义项10', '0001AA1000000028KE4L', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def11', '自定义项11', '0001AA1000000028KE4M', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def15', '自定义项15', '0001AA1000000028KE4Q', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def16', '自定义项16', '0001AA1000000028KE4R', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def17', '自定义项17', '0001AA1000000028KE4S', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def18', '自定义项18', '0001AA1000000028KE4T', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def19', '自定义项19', '0001AA1000000028KE4U', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def2', '自定义项2', '0001AA1000000028KE4V', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def20', '自定义项20', '0001AA1000000028KE4W', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def3', '自定义项3', '0001AA1000000028KE4X', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def4', '自定义项4', '0001AA1000000028KE4Y', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def5', '自定义项5', '0001AA1000000028KE4Z', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def6', '自定义项6', '0001AA1000000028KE50', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def7', '自定义项7', '0001AA1000000028KE51', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def8', '自定义项8', '0001AA1000000028KE52', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def9', '自定义项9', '0001AA1000000028KE53', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 1, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.dr', '删除标识', '0001AA1000000028KE54', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.pk_contract', '合同主键', '0001AA1000000028KE55', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.pk_cumandoc', '客商主键', '0001AA1000000028KE56', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.pk_sale_balance', '主表主键', '0001AA1000000028KE57', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.pk_sale_balance_b', '子表主键', '0001AA1000000028KE58', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.ts', '时间戳', '0001AA1000000028KE59', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('操作员', 5, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.voperatorid', '制单人', '0001AA1000000028KE5A', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.defvoperatorid', '制单人', '0001AA1000000028KE5B', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 2, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 3, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.dmakedate', '制单日期', '0001AA1000000028KE5C', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('操作员', 5, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.vapproveid', '审核人', '0001AA1000000028KE5D', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.defvapproveid', '审核人', '0001AA1000000028KE5E', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 2, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 3, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.dapprovedate', '审核日期', '0001AA1000000028KE5F', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_h.vapprovenote', '审核批语', '0001AA1000000028KE5G', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def12', '自定义项12', '0001AA1000000028KE4N', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def13', '自定义项13', '0001AA1000000028KE4O', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_sale_balance_b.def14', '自定义项14', '0001AA1000000028KE4P', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028KE3P', null, 0, null, null, '2012-11-14 13:00:51', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.vbillno', '单据号', '0001AA1000000028LC1U', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('<nc.ui.ehpta.pub.ref.PeriodRefPane>', 5, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.period', '期间', '0001AA1000000028LC1V', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 6, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.vbillstatus', '单据状态', '0001AA1000000028LC1W', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 1, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.dr', '删除标记', '0001AA1000000028LC1X', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.pk_billtype', '单据类型', '0001AA1000000028LC1Y', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.pk_busitype', '业务类型', '0001AA1000000028LC1Z', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.pk_corp', '公司', '0001AA1000000028LC20', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.pk_saleinv_balance', '主键', '0001AA1000000028LC21', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.ts', '时间戳', '0001AA1000000028LC22', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def1', '自定义字段1', '0001AA1000000028LC23', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def2', '自定义字段2', '0001AA1000000028LC24', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def3', '自定义字段3', '0001AA1000000028LC25', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def4', '自定义字段4', '0001AA1000000028LC26', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def5', '自定义字段5', '0001AA1000000028LC27', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def6', '自定义字段6', '0001AA1000000028LC28', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def7', '自定义字段7', '0001AA1000000028LC29', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def8', '自定义字段8', '0001AA1000000028LC2A', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def9', '自定义字段9', '0001AA1000000028LC2B', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.def10', '自定义字段10', '0001AA1000000028LC2C', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.pk_cumandoc', '客商主键', '0001AA1000000028LC2D', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.custname', '客商名称', '0001AA1000000028LC2E', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.firstmny', '期初货款', '0001AA1000000028LC2F', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.currmny', '本期收入货款', '0001AA1000000028LC2G', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.totalmny', '本期发票金额', '0001AA1000000028LC2H', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.balance', '总余额', '0001AA1000000028LC2I', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 1, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.dr', '删除标识', '0001AA1000000028LC2J', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.pk_saleinv_balance', '主表主键', '0001AA1000000028LC2K', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.pk_saleinv_balance_b', '子表主键', '0001AA1000000028LC2L', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.ts', '时间戳', '0001AA1000000028LC2M', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def1', '自定义项1', '0001AA1000000028LC2N', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def2', '自定义项2', '0001AA1000000028LC2O', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def3', '自定义项3', '0001AA1000000028LC2P', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def4', '自定义项4', '0001AA1000000028LC2Q', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def5', '自定义项5', '0001AA1000000028LC2R', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def6', '自定义项6', '0001AA1000000028LC2S', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def7', '自定义项7', '0001AA1000000028LC2T', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def8', '自定义项8', '0001AA1000000028LC2U', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def9', '自定义项9', '0001AA1000000028LC2V', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def10', '自定义项10', '0001AA1000000028LC2W', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def11', '自定义项11', '0001AA1000000028LC2X', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def12', '自定义项12', '0001AA1000000028LC2Y', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def13', '自定义项13', '0001AA1000000028LC2Z', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def14', '自定义项14', '0001AA1000000028LC30', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def15', '自定义项15', '0001AA1000000028LC31', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def16', '自定义项16', '0001AA1000000028LC32', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def17', '自定义项17', '0001AA1000000028LC33', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def18', '自定义项18', '0001AA1000000028LC34', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def19', '自定义项19', '0001AA1000000028LC35', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_b.def20', '自定义项20', '0001AA1000000028LC36', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('操作员', 5, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.voperatorid', '制单人', '0001AA1000000028LC37', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.defvoperatorid', '制单人', '0001AA1000000028LC38', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 2, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 3, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.dmakedate', '制单日期', '0001AA1000000028LC39', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('操作员', 5, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.vapproveid', '审核人', '0001AA1000000028LC3A', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.defvapproveid', '审核人', '0001AA1000000028LC3B', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 2, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 3, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.dapprovedate', '审核日期', '0001AA1000000028LC3C', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, 0, 'ehpta_calc_saleinv_balance_h.vapprovenote', '审核批语', '0001AA1000000028LC3D', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA1000000028LC1T', null, 0, null, null, '2012-11-21 16:27:48', null, null);

prompt Done.
