  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ehpta.hq010930;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2012-9-13
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class CalcUnderTransfeeBVO extends SuperVO {
           
             public String def5;
             public UFDouble fee;
             public String pk_transfee_b;
             public String pk_transport;
             public String rowno;
             public Integer dr;
             public UFDouble inlandshipfee;
             public String eaddress;
             public String def17;
             public String def11;
             public String transtype;
             public String def14;
             public UFDouble def7;
             public String def16;
             public String def6;
             public String ts;
             public String pk_transfee;
             public String def15;
             public String def10;
             public String pk_sstordoc;
             public UFBoolean settleflag;
             public String def18;
             public String def13;
             public String pk_transport_b;
             public String cgeneralhid;
             public String def8;
             public String def1;
             public UFDouble num;
             public UFDouble piersfee;
             public String saddress;
             public UFDouble carfee;
             public String def12;
             public UFDouble transmny;
             public String def2;
             public String def19;
             public String def4;
             public String cbillno;
             public String def20;
             public UFDate settledate;
             public UFDate sdate;
             public String def3;
             public String def9;
            
             public static final String  DEF5="def5";   
             public static final String  FEE="fee";   
             public static final String  PK_TRANSFEE_B="pk_transfee_b";   
             public static final String  PK_TRANSPORT="pk_transport";   
             public static final String  ROWNO="rowno";   
             public static final String  DR="dr";   
             public static final String  INLANDSHIPFEE="inlandshipfee";   
             public static final String  EADDRESS="eaddress";   
             public static final String  DEF17="def17";   
             public static final String  DEF11="def11";   
             public static final String  TRANSTYPE="transtype";   
             public static final String  DEF14="def14";   
             public static final String  DEF7="def7";   
             public static final String  DEF16="def16";   
             public static final String  DEF6="def6";   
             public static final String  TS="ts";   
             public static final String  PK_TRANSFEE="pk_transfee";   
             public static final String  DEF15="def15";   
             public static final String  DEF10="def10";   
             public static final String  PK_SSTORDOC="pk_sstordoc";   
             public static final String  SETTLEFLAG="settleflag";   
             public static final String  DEF18="def18";   
             public static final String  DEF13="def13";   
             public static final String  PK_TRANSPORT_B="pk_transport_b";   
             public static final String  CGENERALHID="cgeneralhid";   
             public static final String  DEF8="def8";   
             public static final String  DEF1="def1";   
             public static final String  NUM="num";   
             public static final String  PIERSFEE="piersfee";   
             public static final String  SADDRESS="saddress";   
             public static final String  CARFEE="carfee";   
             public static final String  DEF12="def12";   
             public static final String  TRANSMNY="transmny";   
             public static final String  DEF2="def2";   
             public static final String  DEF19="def19";   
             public static final String  DEF4="def4";   
             public static final String  CBILLNO="cbillno";   
             public static final String  DEF20="def20";   
             public static final String  SETTLEDATE="settledate";   
             public static final String  SDATE="sdate";   
             public static final String  DEF3="def3";   
             public static final String  DEF9="def9";   
      
    
        /**
	   * 属性def5的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef5() {
		 return def5;
	  }   
	  
     /**
	   * 属性def5的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef5 String
	   */
	public void setDef5(String newDef5) {
		
		def5 = newDef5;
	 } 	  
       
        /**
	   * 属性fee的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDouble
	   */
	 public UFDouble getFee() {
		 return fee;
	  }   
	  
     /**
	   * 属性fee的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newFee UFDouble
	   */
	public void setFee(UFDouble newFee) {
		
		fee = newFee;
	 } 	  
       
        /**
	   * 属性pk_transfee_b的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getPk_transfee_b() {
		 return pk_transfee_b;
	  }   
	  
     /**
	   * 属性pk_transfee_b的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newPk_transfee_b String
	   */
	public void setPk_transfee_b(String newPk_transfee_b) {
		
		pk_transfee_b = newPk_transfee_b;
	 } 	  
       
        /**
	   * 属性pk_transport的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getPk_transport() {
		 return pk_transport;
	  }   
	  
     /**
	   * 属性pk_transport的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newPk_transport String
	   */
	public void setPk_transport(String newPk_transport) {
		
		pk_transport = newPk_transport;
	 } 	  
       
        /**
	   * 属性rowno的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getRowno() {
		 return rowno;
	  }   
	  
     /**
	   * 属性rowno的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newRowno String
	   */
	public void setRowno(String newRowno) {
		
		rowno = newRowno;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性inlandshipfee的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDouble
	   */
	 public UFDouble getInlandshipfee() {
		 return inlandshipfee;
	  }   
	  
     /**
	   * 属性inlandshipfee的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newInlandshipfee UFDouble
	   */
	public void setInlandshipfee(UFDouble newInlandshipfee) {
		
		inlandshipfee = newInlandshipfee;
	 } 	  
       
        /**
	   * 属性eaddress的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getEaddress() {
		 return eaddress;
	  }   
	  
     /**
	   * 属性eaddress的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newEaddress String
	   */
	public void setEaddress(String newEaddress) {
		
		eaddress = newEaddress;
	 } 	  
       
        /**
	   * 属性def17的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef17() {
		 return def17;
	  }   
	  
     /**
	   * 属性def17的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef17 String
	   */
	public void setDef17(String newDef17) {
		
		def17 = newDef17;
	 } 	  
       
        /**
	   * 属性def11的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef11() {
		 return def11;
	  }   
	  
     /**
	   * 属性def11的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef11 String
	   */
	public void setDef11(String newDef11) {
		
		def11 = newDef11;
	 } 	  
       
        /**
	   * 属性transtype的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getTranstype() {
		 return transtype;
	  }   
	  
     /**
	   * 属性transtype的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newTranstype String
	   */
	public void setTranstype(String newTranstype) {
		
		transtype = newTranstype;
	 } 	  
       
        /**
	   * 属性def14的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef14() {
		 return def14;
	  }   
	  
     /**
	   * 属性def14的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef14 String
	   */
	public void setDef14(String newDef14) {
		
		def14 = newDef14;
	 } 	  
       
        /**
	   * 属性def7的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public UFDouble getDef7() {
		 return def7;
	  }   
	  
     /**
	   * 属性def7的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef7 String
	   */
	public void setDef7(UFDouble newDef7) {
		
		def7 = newDef7;
	 } 	  
       
        /**
	   * 属性def16的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef16() {
		 return def16;
	  }   
	  
     /**
	   * 属性def16的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef16 String
	   */
	public void setDef16(String newDef16) {
		
		def16 = newDef16;
	 } 	  
       
        /**
	   * 属性def6的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef6() {
		 return def6;
	  }   
	  
     /**
	   * 属性def6的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef6 String
	   */
	public void setDef6(String newDef6) {
		
		def6 = newDef6;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDateTime
	   */
	 public String getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性pk_transfee的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getPk_transfee() {
		 return pk_transfee;
	  }   
	  
     /**
	   * 属性pk_transfee的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newPk_transfee String
	   */
	public void setPk_transfee(String newPk_transfee) {
		
		pk_transfee = newPk_transfee;
	 } 	  
       
        /**
	   * 属性def15的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef15() {
		 return def15;
	  }   
	  
     /**
	   * 属性def15的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef15 String
	   */
	public void setDef15(String newDef15) {
		
		def15 = newDef15;
	 } 	  
       
        /**
	   * 属性def10的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef10() {
		 return def10;
	  }   
	  
     /**
	   * 属性def10的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef10 String
	   */
	public void setDef10(String newDef10) {
		
		def10 = newDef10;
	 } 	  
       
        /**
	   * 属性pk_sstordoc的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getPk_sstordoc() {
		 return pk_sstordoc;
	  }   
	  
     /**
	   * 属性pk_sstordoc的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newPk_sstordoc String
	   */
	public void setPk_sstordoc(String newPk_sstordoc) {
		
		pk_sstordoc = newPk_sstordoc;
	 } 	  
       
        /**
	   * 属性settleflag的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFBoolean
	   */
	 public UFBoolean getSettleflag() {
		 return settleflag;
	  }   
	  
     /**
	   * 属性settleflag的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newSettleflag UFBoolean
	   */
	public void setSettleflag(UFBoolean newSettleflag) {
		
		settleflag = newSettleflag;
	 } 	  
       
        /**
	   * 属性def18的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef18() {
		 return def18;
	  }   
	  
     /**
	   * 属性def18的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef18 String
	   */
	public void setDef18(String newDef18) {
		
		def18 = newDef18;
	 } 	  
       
        /**
	   * 属性def13的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef13() {
		 return def13;
	  }   
	  
     /**
	   * 属性def13的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef13 String
	   */
	public void setDef13(String newDef13) {
		
		def13 = newDef13;
	 } 	  
       
        /**
	   * 属性pk_transport_b的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getPk_transport_b() {
		 return pk_transport_b;
	  }   
	  
     /**
	   * 属性pk_transport_b的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newPk_transport_b String
	   */
	public void setPk_transport_b(String newPk_transport_b) {
		
		pk_transport_b = newPk_transport_b;
	 } 	  
       
        /**
	   * 属性cgeneralhid的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getCgeneralhid() {
		 return cgeneralhid;
	  }   
	  
     /**
	   * 属性cgeneralhid的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newCgeneralhid String
	   */
	public void setCgeneralhid(String newCgeneralhid) {
		
		cgeneralhid = newCgeneralhid;
	 } 	  
       
        /**
	   * 属性def8的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef8() {
		 return def8;
	  }   
	  
     /**
	   * 属性def8的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef8 String
	   */
	public void setDef8(String newDef8) {
		
		def8 = newDef8;
	 } 	  
       
        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef1() {
		 return def1;
	  }   
	  
     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef1 String
	   */
	public void setDef1(String newDef1) {
		
		def1 = newDef1;
	 } 	  
       
        /**
	   * 属性num的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDouble
	   */
	 public UFDouble getNum() {
		 return num;
	  }   
	  
     /**
	   * 属性num的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newNum UFDouble
	   */
	public void setNum(UFDouble newNum) {
		
		num = newNum;
	 } 	  
       
        /**
	   * 属性piersfee的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDouble
	   */
	 public UFDouble getPiersfee() {
		 return piersfee;
	  }   
	  
     /**
	   * 属性piersfee的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newPiersfee UFDouble
	   */
	public void setPiersfee(UFDouble newPiersfee) {
		
		piersfee = newPiersfee;
	 } 	  
       
        /**
	   * 属性saddress的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getSaddress() {
		 return saddress;
	  }   
	  
     /**
	   * 属性saddress的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newSaddress String
	   */
	public void setSaddress(String newSaddress) {
		
		saddress = newSaddress;
	 } 	  
       
        /**
	   * 属性carfee的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDouble
	   */
	 public UFDouble getCarfee() {
		 return carfee;
	  }   
	  
     /**
	   * 属性carfee的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newCarfee UFDouble
	   */
	public void setCarfee(UFDouble newCarfee) {
		
		carfee = newCarfee;
	 } 	  
       
        /**
	   * 属性def12的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef12() {
		 return def12;
	  }   
	  
     /**
	   * 属性def12的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef12 String
	   */
	public void setDef12(String newDef12) {
		
		def12 = newDef12;
	 } 	  
       
        /**
	   * 属性transmny的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDouble
	   */
	 public UFDouble getTransmny() {
		 return transmny;
	  }   
	  
     /**
	   * 属性transmny的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newTransmny UFDouble
	   */
	public void setTransmny(UFDouble newTransmny) {
		
		transmny = newTransmny;
	 } 	  
       
        /**
	   * 属性def2的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef2() {
		 return def2;
	  }   
	  
     /**
	   * 属性def2的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef2 String
	   */
	public void setDef2(String newDef2) {
		
		def2 = newDef2;
	 } 	  
       
        /**
	   * 属性def19的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef19() {
		 return def19;
	  }   
	  
     /**
	   * 属性def19的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef19 String
	   */
	public void setDef19(String newDef19) {
		
		def19 = newDef19;
	 } 	  
       
        /**
	   * 属性def4的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef4() {
		 return def4;
	  }   
	  
     /**
	   * 属性def4的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef4 String
	   */
	public void setDef4(String newDef4) {
		
		def4 = newDef4;
	 } 	  
       
        /**
	   * 属性cbillno的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getCbillno() {
		 return cbillno;
	  }   
	  
     /**
	   * 属性cbillno的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newCbillno String
	   */
	public void setCbillno(String newCbillno) {
		
		cbillno = newCbillno;
	 } 	  
       
        /**
	   * 属性def20的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef20() {
		 return def20;
	  }   
	  
     /**
	   * 属性def20的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef20 String
	   */
	public void setDef20(String newDef20) {
		
		def20 = newDef20;
	 } 	  
       
        /**
	   * 属性settledate的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDate
	   */
	 public UFDate getSettledate() {
		 return settledate;
	  }   
	  
     /**
	   * 属性settledate的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newSettledate UFDate
	   */
	public void setSettledate(UFDate newSettledate) {
		
		settledate = newSettledate;
	 } 	  
       
        /**
	   * 属性sdate的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return UFDate
	   */
	 public UFDate getSdate() {
		 return sdate;
	  }   
	  
     /**
	   * 属性sdate的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newSdate UFDate
	   */
	public void setSdate(UFDate newSdate) {
		
		sdate = newSdate;
	 } 	  
       
        /**
	   * 属性def3的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef3() {
		 return def3;
	  }   
	  
     /**
	   * 属性def3的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef3 String
	   */
	public void setDef3(String newDef3) {
		
		def3 = newDef3;
	 } 	  
       
        /**
	   * 属性def9的Getter方法.
	   *
	   * 创建日期:2012-9-13
	   * @return String
	   */
	 public String getDef9() {
		 return def9;
	  }   
	  
     /**
	   * 属性def9的Setter方法.
	   *
	   * 创建日期:2012-9-13
	   * @param newDef9 String
	   */
	public void setDef9(String newDef9) {
		
		def9 = newDef9;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2012-9-13
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_transfee_b == null) {
			errFields.add(new String("pk_transfee_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-9-13
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_transfee";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-9-13
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_transfee_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2012-9-13
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ehpta_calc_under_transfee_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-9-13
	  */
	public CalcUnderTransfeeBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2012-9-13
	 * @param newPk_transfee_b 主键值
	 */
	 public CalcUnderTransfeeBVO(String newPk_transfee_b) {
		
		// 为主键字段赋值:
		 pk_transfee_b = newPk_transfee_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-9-13
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_transfee_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-9-13
	  * @param newPk_transfee_b  String    
	  */
	 public void setPrimaryKey(String newPk_transfee_b) {
				
				pk_transfee_b = newPk_transfee_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2012-9-13
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ehpta_calc_under_transfee_b"; 
				
	 } 
} 
