  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.eh.stock.z06005;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * 司磅单
 * 创建日期:2008-4-11
 * @author author
 * @version Your Project 1.0
 */
     public class SbbillVO extends SuperVO {
           
             public String pk_corp;
             public UFDate dmakedate;
             public String def_3;
             public String def_1;
             public String pk_sbbill;
             public Integer sbtype;
             public Integer dr;
             public UFDouble def_9;
             public String def_10;
             public UFDouble singleweight;
             public UFDouble wrapperweight;
             public String def_2;
             public UFDouble def_8;
             public String vsourcebilltype;
             public String coperatorid;
             public String pk_busitype;
             public UFDateTime ts;
             public UFDouble suttle;
             public String shname;
             public String vsourcebillrowid;
             public String carnumber;
             public String memo;
             public UFDouble fullload;
             public UFDouble packnum;
             public UFDouble def_6;
             public UFDouble bzkz;
             public UFDouble emptyload;
             public String pk_cubasdoc;
             public String def_5;
             public String vbilltype;
             public String reason;
             public Integer numbertype;
             public String def_4;
             public UFDouble def_7;
             public String vsourcebillid;
             public String billno;
             public UFBoolean close_flag;
             public String pk_invbasdoc;
             public UFBoolean ycy_flag;
             public UFDouble sumsuttle;
             public String def_11;
             public String def_12;
             public String tranno;
             public String cppks;
             public UFBoolean ischeck;
             public String def_13;
             public String def_14;
             public String vsourcebillno;
             public UFDouble thamount;
             public String vapprovenote;
             public UFDate dapprovedate;
             public Integer vbillstatus;
             public String vapproveid;
             public String endperson;
             public UFBoolean readflag;//是否取数
             
             public UFBoolean getReadflag() {
				return readflag;
			}

			public void setReadflag(UFBoolean readflag) {
				this.readflag = readflag;
			}

			public String getEndperson() {
				return endperson;
			}

			public void setEndperson(String endperson) {
				this.endperson = endperson;
			}

			public UFDouble getThamount() {
				return thamount;
			}

			public void setThamount(UFDouble thamount) {
				this.thamount = thamount;
			}

			public String getVsourcebillno() {
				return vsourcebillno;
			}

			public void setVsourcebillno(String vsourcebillno) {
				this.vsourcebillno = vsourcebillno;
			}

			/**
             * @return the def_13
             */
            public String getDef_13() {
                return def_13;
            }

            /**
             * @param def_13 the def_13 to set
             */
            public void setDef_13(String def_13) {
                this.def_13 = def_13;
            }

            /**
             * @return the def_14
             */
            public String getDef_14() {
                return def_14;
            }

            /**
             * @param def_14 the def_14 to set
             */
            public void setDef_14(String def_14) {
                this.def_14 = def_14;
            }

            public String getCppks() {
				return cppks;
			}

			public void setCppks(String cppks) {
				this.cppks = cppks;
			}

			public String getTranno() {
				return tranno;
			}

			public void setTranno(String tranno) {
				this.tranno = tranno;
			}

			/**
             * @return the def_12
             */
            public String getDef_12() {
                return def_12;
            }

            /**
             * @param def_12 the def_12 to set
             */
            public void setDef_12(String def_12) {
                this.def_12 = def_12;
            }

            /**
             * @return the def_11
             */
            public String getDef_11() {
                return def_11;
            }

            /**
             * @param def_11 the def_11 to set
             */
            public void setDef_11(String def_11) {
                this.def_11 = def_11;
            }

    public UFDouble getSumsuttle() {
				return sumsuttle;
			}

	public void setSumsuttle(UFDouble sumsuttle) {
		this.sumsuttle = sumsuttle;
	}

	/**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性dmakedate的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDate
	   */
	 public UFDate getDmakedate() {
		 return dmakedate;
	  }   
	  
     /**
	   * 属性dmakedate的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDmakedate UFDate
	   */
	public void setDmakedate(UFDate newDmakedate) {
		
		dmakedate = newDmakedate;
	 } 	  
       
        /**
	   * 属性def_3的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getDef_3() {
		 return def_3;
	  }   
	  
     /**
	   * 属性def_3的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_3 String
	   */
	public void setDef_3(String newDef_3) {
		
		def_3 = newDef_3;
	 } 	  
       
        /**
	   * 属性def_1的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getDef_1() {
		 return def_1;
	  }   
	  
     /**
	   * 属性def_1的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_1 String
	   */
	public void setDef_1(String newDef_1) {
		
		def_1 = newDef_1;
	 } 	  
       
        /**
	   * 属性pk_sbbill的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getPk_sbbill() {
		 return pk_sbbill;
	  }   
	  
     /**
	   * 属性pk_sbbill的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newPk_sbbill String
	   */
	public void setPk_sbbill(String newPk_sbbill) {
		
		pk_sbbill = newPk_sbbill;
	 } 	  
       
        /**
	   * 属性sbtype的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public Integer getSbtype() {
		 return sbtype;
	  }   
	    
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性def_9的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getDef_9() {
		 return def_9;
	  }   
	  
     /**
	   * 属性def_9的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_9 UFDouble
	   */
	public void setDef_9(UFDouble newDef_9) {
		
		def_9 = newDef_9;
	 } 	  
       
        /**
	   * 属性def_10的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public String getDef_10() {
		 return def_10;
	  }   
	  
     /**
	   * 属性def_10的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_10 UFDouble
	   */
	public void setDef_10(String newDef_10) {
		
		def_10 = newDef_10;
	 } 	  
       
        /**
	   * 属性singleweight的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getSingleweight() {
		 return singleweight;
	  }   
	  
     /**
	   * 属性singleweight的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newSingleweight UFDouble
	   */
	public void setSingleweight(UFDouble newSingleweight) {
		
		singleweight = newSingleweight;
	 } 	  
       
        /**
	   * 属性wrapperweight的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getWrapperweight() {
		 return wrapperweight;
	  }   
	  
     /**
	   * 属性wrapperweight的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newWrapperweight UFDouble
	   */
	public void setWrapperweight(UFDouble newWrapperweight) {
		
		wrapperweight = newWrapperweight;
	 } 	  
       
        /**
	   * 属性def_2的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getDef_2() {
		 return def_2;
	  }   
	  
     /**
	   * 属性def_2的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_2 String
	   */
	public void setDef_2(String newDef_2) {
		
		def_2 = newDef_2;
	 } 	  
       
        /**
	   * 属性def_8的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getDef_8() {
		 return def_8;
	  }   
	  
     /**
	   * 属性def_8的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_8 UFDouble
	   */
	public void setDef_8(UFDouble newDef_8) {
		
		def_8 = newDef_8;
	 } 	  
       
        /**
	   * 属性vsourcebilltype的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getVsourcebilltype() {
		 return vsourcebilltype;
	  }   
	  
     /**
	   * 属性vsourcebilltype的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newVsourcebilltype String
	   */
	public void setVsourcebilltype(String newVsourcebilltype) {
		
		vsourcebilltype = newVsourcebilltype;
	 } 	  
       
        /**
	   * 属性coperatorid的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getCoperatorid() {
		 return coperatorid;
	  }   
	  
     /**
	   * 属性coperatorid的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newCoperatorid String
	   */
	public void setCoperatorid(String newCoperatorid) {
		
		coperatorid = newCoperatorid;
	 } 	  
       
        /**
	   * 属性pk_busitype的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getPk_busitype() {
		 return pk_busitype;
	  }   
	  
     /**
	   * 属性pk_busitype的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newPk_busitype String
	   */
	public void setPk_busitype(String newPk_busitype) {
		
		pk_busitype = newPk_busitype;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性suttle的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getSuttle() {
		 return suttle;
	  }   
	  
     /**
	   * 属性suttle的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newSuttle UFDouble
	   */
	public void setSuttle(UFDouble newSuttle) {
		
		suttle = newSuttle;
	 } 	  
       
        /**
	   * 属性shname的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getShname() {
		 return shname;
	  }   
	  
     /**
	   * 属性shname的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newShname String
	   */
	public void setShname(String newShname) {
		
		shname = newShname;
	 } 	  
       
        /**
	   * 属性vsourcebillrowid的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getVsourcebillrowid() {
		 return vsourcebillrowid;
	  }   
	  
     /**
	   * 属性vsourcebillrowid的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newVsourcebillrowid String
	   */
	public void setVsourcebillrowid(String newVsourcebillrowid) {
		
		vsourcebillrowid = newVsourcebillrowid;
	 } 	  
       
        /**
	   * 属性carnumber的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getCarnumber() {
		 return carnumber;
	  }   
	  
     /**
	   * 属性carnumber的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newCarnumber String
	   */
	public void setCarnumber(String newCarnumber) {
		
		carnumber = newCarnumber;
	 } 	  
       
        /**
	   * 属性memo的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getMemo() {
		 return memo;
	  }   
	  
     /**
	   * 属性memo的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newMemo String
	   */
	public void setMemo(String newMemo) {
		
		memo = newMemo;
	 } 	  
       
        /**
	   * 属性fullload的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getFullload() {
		 return fullload;
	  }   
	  
     /**
	   * 属性fullload的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newFullload UFDouble
	   */
	public void setFullload(UFDouble newFullload) {
		
		fullload = newFullload;
	 } 	  
       
        /**
	   * 属性packnum的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getPacknum() {
		 return packnum;
	  }   
	  
     /**
	   * 属性packnum的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newPacknum UFDouble
	   */
	public void setPacknum(UFDouble newPacknum) {
		
		packnum = newPacknum;
	 } 	  
       
        /**
	   * 属性def_6的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getDef_6() {
		 return def_6;
	  }   
	  
     /**
	   * 属性def_6的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_6 UFDouble
	   */
	public void setDef_6(UFDouble newDef_6) {
		
		def_6 = newDef_6;
	 } 	  
       
        /**
	   * 属性bzkz的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getBzkz() {
		 return bzkz;
	  }   
	  
     /**
	   * 属性bzkz的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newBzkz UFDouble
	   */
	public void setBzkz(UFDouble newBzkz) {
		
		bzkz = newBzkz;
	 } 	  
       
        /**
	   * 属性emptyload的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getEmptyload() {
		 return emptyload;
	  }   
	  
     /**
	   * 属性emptyload的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newEmptyload UFDouble
	   */
	public void setEmptyload(UFDouble newEmptyload) {
		
		emptyload = newEmptyload;
	 } 	  
       
        /**
	   * 属性pk_cubasdoc的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getPk_cubasdoc() {
		 return pk_cubasdoc;
	  }   
	  
     /**
	   * 属性pk_cubasdoc的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newPk_cubasdoc String
	   */
	public void setPk_cubasdoc(String newPk_cubasdoc) {
		
		pk_cubasdoc = newPk_cubasdoc;
	 } 	  
       
        /**
	   * 属性def_5的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getDef_5() {
		 return def_5;
	  }   
	  
     /**
	   * 属性def_5的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_5 String
	   */
	public void setDef_5(String newDef_5) {
		
		def_5 = newDef_5;
	 } 	  
       
        /**
	   * 属性vbilltype的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getVbilltype() {
		 return vbilltype;
	  }   
	  
     /**
	   * 属性vbilltype的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newVbilltype String
	   */
	public void setVbilltype(String newVbilltype) {
		
		vbilltype = newVbilltype;
	 } 	  
       
        /**
	   * 属性reason的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getReason() {
		 return reason;
	  }   
	  
     /**
	   * 属性reason的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newReason String
	   */
	public void setReason(String newReason) {
		
		reason = newReason;
	 } 	  
       
        /**
	   * 属性numbertype的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public Integer getNumbertype() {
		 return numbertype;
	  }   
	    
       
        /**
	   * 属性def_4的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getDef_4() {
		 return def_4;
	  }   
	  
     /**
	   * 属性def_4的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_4 String
	   */
	public void setDef_4(String newDef_4) {
		
		def_4 = newDef_4;
	 } 	  
       
        /**
	   * 属性def_7的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return UFDouble
	   */
	 public UFDouble getDef_7() {
		 return def_7;
	  }   
	  
     /**
	   * 属性def_7的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newDef_7 UFDouble
	   */
	public void setDef_7(UFDouble newDef_7) {
		
		def_7 = newDef_7;
	 } 	  
       
        /**
	   * 属性vsourcebillid的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getVsourcebillid() {
		 return vsourcebillid;
	  }   
	  
     /**
	   * 属性vsourcebillid的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newVsourcebillid String
	   */
	public void setVsourcebillid(String newVsourcebillid) {
		
		vsourcebillid = newVsourcebillid;
	 } 	  
       
        /**
	   * 属性billno的Getter方法.
	   *
	   * 创建日期:2008-4-11
	   * @return String
	   */
	 public String getBillno() {
		 return billno;
	  }   
	  
     /**
	   * 属性billno的Setter方法.
	   *
	   * 创建日期:2008-4-11
	   * @param newBillno String
	   */
	public void setBillno(String newBillno) {
		
		billno = newBillno;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2008-4-11
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_sbbill == null) {
			errFields.add(new String("pk_sbbill"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2008-4-11
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2008-4-11
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_sbbill";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2008-4-11
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "eh_sbbill";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2008-4-11
	  */
	public SbbillVO() {
		super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2008-4-11
	 * @param newPk_sbbill 主键值
	 */
	 public SbbillVO(String newPk_sbbill) {
		
		// 为主键字段赋值:
		 pk_sbbill = newPk_sbbill;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2008-4-11
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_sbbill;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2008-4-11
	  * @param newPk_sbbill  String    
	  */
	 public void setPrimaryKey(String newPk_sbbill) {
				
				pk_sbbill = newPk_sbbill; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2008-4-11
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "eh_sbbill"; 
				
	 }

    /**
     * @return the close_flag
     */
    public UFBoolean getClose_flag() {
        return close_flag;
    }

    /**
     * @param close_flag the close_flag to set
     */
    public void setClose_flag(UFBoolean close_flag) {
        this.close_flag = close_flag;
    }

    /**
     * @return the pk_invbasdoc
     */
    public String getPk_invbasdoc() {
        return pk_invbasdoc;
    }

    /**
     * @param pk_invbasdoc the pk_invbasdoc to set
     */
    public void setPk_invbasdoc(String pk_invbasdoc) {
        this.pk_invbasdoc = pk_invbasdoc;
    }

    /**
     * @param numbertype the numbertype to set
     */
    public void setNumbertype(Integer numbertype) {
        this.numbertype = numbertype;
    }

    /**
     * @param sbtype the sbtype to set
     */
    public void setSbtype(Integer sbtype) {
        this.sbtype = sbtype;
    }

	public UFBoolean getYcy_flag() {
		return ycy_flag;
	}

	public void setYcy_flag(UFBoolean ycy_flag) {
		this.ycy_flag = ycy_flag;
	}

	public UFBoolean getIscheck() {
		return ischeck;
	}

	public void setIscheck(UFBoolean ischeck) {
		this.ischeck = ischeck;
	}

	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	public void setDapprovedate(UFDate dapprovedate) {
		this.dapprovedate = dapprovedate;
	}

	public String getVapproveid() {
		return vapproveid;
	}

	public void setVapproveid(String vapproveid) {
		this.vapproveid = vapproveid;
	}

	public String getVapprovenote() {
		return vapprovenote;
	}

	public void setVapprovenote(String vapprovenote) {
		this.vapprovenote = vapprovenote;
	}

	public Integer getVbillstatus() {
		return vbillstatus;
	}

	public void setVbillstatus(Integer vbillstatus) {
		this.vbillstatus = vbillstatus;
	} 
} 
