/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ehpta.hq010201;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-7-2
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class StorcontractBVO extends SuperVO {

	public String def5;
	public UFDouble extrafare;
	public String pk_corp;
	public String pk_cargdoc;
	public Integer dr;
	public String storname;
	public String pk_storagedoc;
	public Integer concesessionsday;
	public String def7;
	public String pk_invbasdoc;
	public String storccontracttype;
	public String def6;
	public UFDouble outmny;
	public UFDateTime ts;
	public UFDouble custodymny;
	public String outunit;
	public String def10;
	public String pk_storedoc;
	public String memo;
	public String def8;
	public String storunit;
	public String importcontracttype;
	public String spec;
	public String invname;
	public String def1;
	public String def2;
	public UFDouble stormny;
	public String def4;
	public UFDouble entermny;
	public String def3;
	public String def9;
	public String pk_storcontract_b;
	public String feetype;
	public UFDouble signprice;

	public static final String DEF5 = "def5";
	public static final String EXTRAFARE = "extrafare";
	public static final String PK_CORP = "pk_corp";
	public static final String PK_CARGDOC = "pk_cargdoc";
	public static final String DR = "dr";
	public static final String STORNAME = "storname";
	public static final String PK_STORAGEDOC = "pk_storagedoc";
	public static final String CONCESESSIONSDAY = "concesessionsday";
	public static final String DEF7 = "def7";
	public static final String PK_INVBASDOC = "pk_invbasdoc";
	public static final String STORCCONTRACTTYPE = "storccontracttype";
	public static final String DEF6 = "def6";
	public static final String OUTMNY = "outmny";
	public static final String TS = "ts";
	public static final String CUSTODYMNY = "custodymny";
	public static final String OUTUNIT = "outunit";
	public static final String DEF10 = "def10";
	public static final String PK_STOREDOC = "pk_storedoc";
	public static final String MEMO = "memo";
	public static final String DEF8 = "def8";
	public static final String STORUNIT = "storunit";
	public static final String IMPORTCONTRACTTYPE = "importcontracttype";
	public static final String SPEC = "spec";
	public static final String INVNAME = "invname";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String STORMNY = "stormny";
	public static final String DEF4 = "def4";
	public static final String ENTERMNY = "entermny";
	public static final String DEF3 = "def3";
	public static final String DEF9 = "def9";
	public static final String PK_STORCONTRACT_B = "pk_storcontract_b";

	public String getFeetype() {
		return feetype;
	}

	public void setFeetype(String feetype) {
		this.feetype = feetype;
	}

	public UFDouble getSignprice() {
		return signprice;
	}

	public void setSignprice(UFDouble signprice) {
		this.signprice = signprice;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性extrafare的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDouble
	 */
	public UFDouble getExtrafare() {
		return extrafare;
	}

	/**
	 * 属性extrafare的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newExtrafare
	 *            UFDouble
	 */
	public void setExtrafare(UFDouble newExtrafare) {

		extrafare = newExtrafare;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性pk_cargdoc的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_cargdoc() {
		return pk_cargdoc;
	}

	/**
	 * 属性pk_cargdoc的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_cargdoc
	 *            String
	 */
	public void setPk_cargdoc(String newPk_cargdoc) {

		pk_cargdoc = newPk_cargdoc;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性storname的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getStorname() {
		return storname;
	}

	/**
	 * 属性storname的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStorname
	 *            String
	 */
	public void setStorname(String newStorname) {

		storname = newStorname;
	}

	/**
	 * 属性pk_storagedoc的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_storagedoc() {
		return pk_storagedoc;
	}

	/**
	 * 属性pk_storagedoc的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storagedoc
	 *            String
	 */
	public void setPk_storagedoc(String newPk_storagedoc) {

		pk_storagedoc = newPk_storagedoc;
	}

	/**
	 * 属性concesessionsday的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getConcesessionsday() {
		return concesessionsday;
	}

	/**
	 * 属性concesessionsday的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newConcesessionsday
	 *            Integer
	 */
	public void setConcesessionsday(Integer newConcesessionsday) {

		concesessionsday = newConcesessionsday;
	}

	/**
	 * 属性def7的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef7
	 *            String
	 */
	public void setDef7(String newDef7) {

		def7 = newDef7;
	}

	/**
	 * 属性pk_invbasdoc的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_invbasdoc() {
		return pk_invbasdoc;
	}

	/**
	 * 属性pk_invbasdoc的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_invbasdoc
	 *            String
	 */
	public void setPk_invbasdoc(String newPk_invbasdoc) {

		pk_invbasdoc = newPk_invbasdoc;
	}

	/**
	 * 属性storccontracttype的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getStorccontracttype() {
		return storccontracttype;
	}

	/**
	 * 属性storccontracttype的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStorccontracttype
	 *            String
	 */
	public void setStorccontracttype(String newStorccontracttype) {

		storccontracttype = newStorccontracttype;
	}

	/**
	 * 属性def6的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef6
	 *            String
	 */
	public void setDef6(String newDef6) {

		def6 = newDef6;
	}

	/**
	 * 属性outmny的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDouble
	 */
	public UFDouble getOutmny() {
		return outmny;
	}

	/**
	 * 属性outmny的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newOutmny
	 *            UFDouble
	 */
	public void setOutmny(UFDouble newOutmny) {

		outmny = newOutmny;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newTs
	 *            String
	 */
	public void setTs(String newTs) {

		ts = new UFDateTime(newTs);
	}

	/**
	 * 属性custodymny的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDouble
	 */
	public UFDouble getCustodymny() {
		return custodymny;
	}

	/**
	 * 属性custodymny的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newCustodymny
	 *            UFDouble
	 */
	public void setCustodymny(UFDouble newCustodymny) {

		custodymny = newCustodymny;
	}

	/**
	 * 属性outunit的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getOutunit() {
		return outunit;
	}

	/**
	 * 属性outunit的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newOutunit
	 *            String
	 */
	public void setOutunit(String newOutunit) {

		outunit = newOutunit;
	}

	/**
	 * 属性def10的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef10
	 *            String
	 */
	public void setDef10(String newDef10) {

		def10 = newDef10;
	}

	/**
	 * 属性pk_storedoc的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_storedoc() {
		return pk_storedoc;
	}

	/**
	 * 属性pk_storedoc的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storedoc
	 *            String
	 */
	public void setPk_storedoc(String newPk_storedoc) {

		pk_storedoc = newPk_storedoc;
	}

	/**
	 * 属性memo的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * 属性memo的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {

		memo = newMemo;
	}

	/**
	 * 属性def8的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef8
	 *            String
	 */
	public void setDef8(String newDef8) {

		def8 = newDef8;
	}

	/**
	 * 属性storunit的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getStorunit() {
		return storunit;
	}

	/**
	 * 属性storunit的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStorunit
	 *            String
	 */
	public void setStorunit(String newStorunit) {

		storunit = newStorunit;
	}

	/**
	 * 属性importcontracttype的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getImportcontracttype() {
		return importcontracttype;
	}

	/**
	 * 属性importcontracttype的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newImportcontracttype
	 *            String
	 */
	public void setImportcontracttype(String newImportcontracttype) {

		importcontracttype = newImportcontracttype;
	}

	/**
	 * 属性spec的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getSpec() {
		return spec;
	}

	/**
	 * 属性spec的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newSpec
	 *            String
	 */
	public void setSpec(String newSpec) {

		spec = newSpec;
	}

	/**
	 * 属性invname的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getInvname() {
		return invname;
	}

	/**
	 * 属性invname的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newInvname
	 *            String
	 */
	public void setInvname(String newInvname) {

		invname = newInvname;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性stormny的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDouble
	 */
	public UFDouble getStormny() {
		return stormny;
	}

	/**
	 * 属性stormny的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStormny
	 *            UFDouble
	 */
	public void setStormny(UFDouble newStormny) {

		stormny = newStormny;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性entermny的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDouble
	 */
	public UFDouble getEntermny() {
		return entermny;
	}

	/**
	 * 属性entermny的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newEntermny
	 *            UFDouble
	 */
	public void setEntermny(UFDouble newEntermny) {

		entermny = newEntermny;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性def9的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef9
	 *            String
	 */
	public void setDef9(String newDef9) {

		def9 = newDef9;
	}

	/**
	 * 属性pk_storcontract_b的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_storcontract_b() {
		return pk_storcontract_b;
	}

	/**
	 * 属性pk_storcontract_b的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storcontract_b
	 *            String
	 */
	public void setPk_storcontract_b(String newPk_storcontract_b) {

		pk_storcontract_b = newPk_storcontract_b;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "pk_storagedoc";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_storcontract_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "ehpta_storcontract_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-7-2
	 */
	public StorcontractBVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storcontract_b
	 *            主键值
	 */
	public StorcontractBVO(String newPk_storcontract_b) {

		// 为主键字段赋值:
		pk_storcontract_b = newPk_storcontract_b;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_storcontract_b;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storcontract_b
	 *            String
	 */
	public void setPrimaryKey(String newPk_storcontract_b) {

		pk_storcontract_b = newPk_storcontract_b;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "ehpta_storcontract_b";

	}
}
