/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ehpta.hq010201;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-7-2
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class StorContractVO extends SuperVO {

	public String def5;
	public String pk_corp;
	public String signperson;
	public String pk_stordoc;
	public UFDate dmakedate;
	public String pk_billtype;
	public Integer dr;
	public String pk_customer;
	public String pk_storagedoc;
	public String def7;
	public Integer vbillstatus;
	public UFDate stopdate;
	public UFDate dapprovedate;
	public String voperatorid;
	public String def6;
	public String pk_busitype;
	public UFDateTime ts;
	public String def10;
	public String memo;
	public String def8;
	public String def1;
	public UFBoolean ty_flag;
	public UFDate signdate;
	public String vapproveid;
	public String def2;
	public String signcompany;
	public String pk_area;
	public Integer concessionsday;
	public UFDouble entrycharge;
	public UFDate edate;
	public String vapprovenote;
	public String def4;
	public String vbillno;
	public UFDate sdate;
	public String def3;
	public String def9;
	public String storaddr;
	
	public String getStoraddr() {
		return storaddr;
	}

	public void setStoraddr(String storaddr) {
		this.storaddr = storaddr;
	}

	public String getPk_billtype() {
		return pk_billtype;
	}

	public void setPk_billtype(String pk_billtype) {
		this.pk_billtype = pk_billtype;
	}

	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	public void setDapprovedate(UFDate dapprovedate) {
		this.dapprovedate = dapprovedate;
	}

	public String getVoperatorid() {
		return voperatorid;
	}

	public void setVoperatorid(String voperatorid) {
		this.voperatorid = voperatorid;
	}

	public String getVbillno() {
		return vbillno;
	}

	public void setVbillno(String vbillno) {
		this.vbillno = vbillno;
	}


	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性signperson的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getSignperson() {
		return signperson;
	}

	/**
	 * 属性signperson的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newSignperson
	 *            String
	 */
	public void setSignperson(String newSignperson) {

		signperson = newSignperson;
	}

	/**
	 * 属性pk_stordoc的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_stordoc() {
		return pk_stordoc;
	}

	/**
	 * 属性pk_stordoc的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_stordoc
	 *            String
	 */
	public void setPk_stordoc(String newPk_stordoc) {

		pk_stordoc = newPk_stordoc;
	}

	/**
	 * 属性dmakedate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getDmakedate() {
		return dmakedate;
	}

	/**
	 * 属性dmakedate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDmakedate
	 *            UFDate
	 */
	public void setDmakedate(UFDate newDmakedate) {

		dmakedate = newDmakedate;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性pk_customer的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_customer() {
		return pk_customer;
	}

	/**
	 * 属性pk_customer的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_customer
	 *            String
	 */
	public void setPk_customer(String newPk_customer) {

		pk_customer = newPk_customer;
	}

	/**
	 * 属性pk_storagedoc的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_storagedoc() {
		return pk_storagedoc;
	}

	/**
	 * 属性pk_storagedoc的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storagedoc
	 *            String
	 */
	public void setPk_storagedoc(String newPk_storagedoc) {

		pk_storagedoc = newPk_storagedoc;
	}

	/**
	 * 属性def7的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef7
	 *            String
	 */
	public void setDef7(String newDef7) {

		def7 = newDef7;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性stopdate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getStopdate() {
		return stopdate;
	}

	/**
	 * 属性stopdate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newStopdate
	 *            UFDate
	 */
	public void setStopdate(UFDate newStopdate) {

		stopdate = newStopdate;
	}

	/**
	 * 属性def6的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef6
	 *            String
	 */
	public void setDef6(String newDef6) {

		def6 = newDef6;
	}

	/**
	 * 属性pk_busitype的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_busitype() {
		return pk_busitype;
	}

	/**
	 * 属性pk_busitype的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_busitype
	 *            String
	 */
	public void setPk_busitype(String newPk_busitype) {

		pk_busitype = newPk_busitype;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(String newTs) {

		ts = new UFDateTime(newTs);
	}

	/**
	 * 属性def10的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef10
	 *            String
	 */
	public void setDef10(String newDef10) {

		def10 = newDef10;
	}

	/**
	 * 属性memo的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * 属性memo的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {

		memo = newMemo;
	}

	/**
	 * 属性def8的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef8
	 *            String
	 */
	public void setDef8(String newDef8) {

		def8 = newDef8;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性ty_flag的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getTy_flag() {
		return ty_flag;
	}

	/**
	 * 属性ty_flag的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newTy_flag
	 *            UFBoolean
	 */
	public void setTy_flag(UFBoolean newTy_flag) {

		ty_flag = newTy_flag;
	}

	/**
	 * 属性signdate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getSigndate() {
		return signdate;
	}

	/**
	 * 属性signdate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newSigndate
	 *            UFDate
	 */
	public void setSigndate(UFDate newSigndate) {

		signdate = newSigndate;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性signcompany的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getSigncompany() {
		return signcompany;
	}

	/**
	 * 属性signcompany的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newSigncompany
	 *            String
	 */
	public void setSigncompany(String newSigncompany) {

		signcompany = newSigncompany;
	}

	/**
	 * 属性pk_area的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPk_area() {
		return pk_area;
	}

	/**
	 * 属性pk_area的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_area
	 *            String
	 */
	public void setPk_area(String newPk_area) {

		pk_area = newPk_area;
	}

	/**
	 * 属性concessionsday的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return Integer
	 */
	public Integer getConcessionsday() {
		return concessionsday;
	}

	/**
	 * 属性concessionsday的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newConcessionsday
	 *            Integer
	 */
	public void setConcessionsday(Integer newConcessionsday) {

		concessionsday = newConcessionsday;
	}

	/**
	 * 属性entrycharge的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDouble
	 */
	public UFDouble getEntrycharge() {
		return entrycharge;
	}

	/**
	 * 属性entrycharge的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newEntrycharge
	 *            UFDouble
	 */
	public void setEntrycharge(UFDouble newEntrycharge) {

		entrycharge = newEntrycharge;
	}

	/**
	 * 属性edate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getEdate() {
		return edate;
	}

	/**
	 * 属性edate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newEdate
	 *            UFDate
	 */
	public void setEdate(UFDate newEdate) {

		edate = newEdate;
	}

	public String getVapprovenote() {
		return vapprovenote;
	}

	public void setVapprovenote(String vapprovenote) {
		this.vapprovenote = vapprovenote;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性sdate的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return UFDate
	 */
	public UFDate getSdate() {
		return sdate;
	}

	/**
	 * 属性sdate的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newSdate
	 *            UFDate
	 */
	public void setSdate(UFDate newSdate) {

		sdate = newSdate;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性def9的Getter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newDef9
	 *            String
	 */
	public void setDef9(String newDef9) {

		def9 = newDef9;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_storagedoc == null) {
			errFields.add(new String("pk_storagedoc"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_storagedoc";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "ehpta_storcontract";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-7-2
	 */
	public StorContractVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storagedoc
	 *            主键值
	 */
	public StorContractVO(String newPk_storagedoc) {

		// 为主键字段赋值:
		pk_storagedoc = newPk_storagedoc;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_storagedoc;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @param newPk_storagedoc
	 *            String
	 */
	public void setPrimaryKey(String newPk_storagedoc) {

		pk_storagedoc = newPk_storagedoc;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-7-2
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "EHPTA_STORCONTRACT";

	}
}
