prompt Importing table pub_query_condition...
set feedback off
set define off
insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 6, 100, 0, null, null, 'ehpta_calc_interest.billtype', '票据类型', '1120ZZ1000000011IZTC', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 4, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:32:07', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 6, 100, 0, null, null, 'ehpta_calc_interest.calcflag', '结算标记', '1120ZZ1000000011IZTD', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 5, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:32:07', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, null, 'ehpta_calc_interest.contno', '合同编号', '1120ZZ1000000011IZTE', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 1, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:32:07', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 100, 0, null, null, 'ehpta_calc_interest.custname', '客户名称', '1120ZZ1000000011IZTF', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 0, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:31:04', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 3, 100, 0, null, null, 'ehpta_calc_interest.dapprovedate', '审核日期', '1120ZZ1000000011IZTG', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 7, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:32:07', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 3, 100, 0, null, null, 'ehpta_calc_interest.dmakedate', '制单日期', '1120ZZ1000000011IZTS', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 6, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:32:07', null, null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 2, 100, 0, null, null, 'ehpta_calc_interest.rate', '利率', '1120ZZ1000000011IZU2', 'N', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 3, '@@@@', '1120ZZ1000000011IZTA', null, 0, null, null, '2012-08-07 08:32:07', null, null);

prompt Done.
