package nc.itf.busisys;


/**
 * This class was generated by NC WS Tools.
 * Thu Aug 04 12:05:44 CST 2011
 * Generated source version: v1312430744911
 * 
 */


public interface IExportXML {

    public void getExportXML()throws Exception;

}
