prompt Importing table bd_billtype...
set feedback off
set define off
insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, 'PTA仓储合同', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010201', null, null, null, null, 'nc.ui.ehpta.hq010201.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010201', null, 'HQ01', null, 'ehpta', '2012-07-02 11:27:11', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, 'PTA运输合同', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010101', null, null, null, null, 'nc.ui.ehpta.hq010101.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010101', null, 'HQ02', null, 'ehpta', '2012-07-02 08:02:36', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, 'PTA挂结价维护', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010301', null, null, null, null, 'nc.ui.ehpta.hq010301.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010301', null, 'HQ03', null, 'ehpta', '2012-07-04 13:11:09', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, null, '现货合同', 'N', 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010401', null, null, null, null, 'nc.ui.ehpta.hq010401.ClientUICheckRule', null, null, 'N', 'Y', 'N', null, 'HQ010401', null, 'HQ04', 'nc.bs.ehpta.dmo.SpotContractDMO', 'ehpta', '2012-07-13 14:48:48', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, null, '长单合同', 'N', 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010402', null, null, null, null, 'nc.ui.ehpta.hq010402.ClientUICheckRule', null, null, 'N', 'Y', 'N', null, 'HQ010402', null, 'HQ06', 'nc.bs.ehpta.dmo.SaleContractDMO', 'ehpta', '2012-07-13 14:48:29', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '余额调整单', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010403', null, null, null, null, 'nc.ui.ehpta.hq010403.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010403', null, 'HQ07', null, 'ehpta', '2012-07-22 20:35:17', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, null, '下游运输合同', 'N', 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010102', null, null, null, null, 'nc.ui.ehpta.hq010101.ClientUICheckRule', null, null, 'N', 'Y', 'N', null, 'HQ010102', null, 'HQ08', null, 'ehpta', '2012-08-23 14:12:55', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '贴息计算', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010901', null, null, null, null, 'nc.ui.ehpta.hq010901.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010901', null, 'HQ09', null, 'ehpta', '2012-08-07 07:18:58', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, null, '挂结价差结算', 'N', 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010910', null, null, null, null, 'nc.ui.ehpta.hq010910.ClientUICheckRule', null, null, 'N', 'Y', 'N', null, 'HQ010910', null, 'HQ10', null, 'ehpta', '2012-08-27 10:58:55', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '上游运费结算', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010920', null, null, null, null, 'nc.ui.ehpta.hq010920.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010920', null, 'HQ11', null, 'ehpta', '2012-09-07 13:46:06', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '下游运费结算', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010930', null, null, null, null, 'nc.ui.ehpta.hq010930.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010930', null, 'HQ12', null, 'ehpta', '2012-09-13 10:39:18', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '仓储装卸费结算', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010940', null, null, null, null, 'nc.ui.ehpta.hq010940.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010940', null, 'HQ13', null, 'ehpta', '2012-09-17 14:38:26', null, null);

insert into bd_billtype (ACCOUNTCLASS, BILLSTYLE, BILLTYPENAME, CANEXTENDTRANSACTION, CHECKCLASSNAME, CLASSNAME, COMPONENT, DATAFINDERCLZ, DEF1, DEF2, DEF3, DR, FORWARDBILLTYPE, ISACCOUNT, ISITEM, ISROOT, ISTRANSACTION, NODECODE, PARENTBILLTYPE, PK_BILLTYPECODE, REFERCLASSNAME, SYSTEMCODE, TS, WEBNODECODE, WHERESTRING)
values (null, 130, '返利统计表', null, 'nc.bs.trade.business.HYSuperDMO', '<Y>HQ010950', null, null, null, null, 'nc.ui.ehpta.hq010950.ClientUICheckRule', null, null, null, 'Y', 'N', null, 'HQ010950', null, 'HQ14', null, 'ehpta', '2012-09-26 14:36:15', null, null);

prompt Done.
