/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ehpta.hq0305;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-11-13
 * 
 * @author author
 * @version Your Project 1.0
 */
public class SaleBalanceBVO extends SuperVO {

	public String def5;
	public UFDouble adtype3;
	public UFDouble salemny;
	public String connamed;
	public UFDouble salebalance;
	public Integer dr;
	public UFDouble adtype4;
	public String def17;
	public String custname;
	public String def11;
	public String def14;
	public String def7;
	public UFDouble balance;
	public String def16;
	public String ts;
	public String def6;
	public UFDouble firstmny;
	public String def15;
	public String pk_contract;
	public String def10;
	public String def18;
	public String def13;
	public String def8;
	public UFDouble currmny;
	public String def1;
	public String pk_cumandoc;
	public String pk_sale_balance_b;
	public String def12;
	public String def2;
	public String concode;
	public String def19;
	public String def4;
	public String def20;
	public UFDouble adtype2;
	public String pk_sale_balance;
	public String def3;
	public String def9;

	public static final String DEF5 = "def5";
	public static final String ADTYPE3 = "adtype3";
	public static final String SALEMNY = "salemny";
	public static final String CONNAMED = "connamed";
	public static final String SALEBALANCE = "salebalance";
	public static final String DR = "dr";
	public static final String ADTYPE4 = "adtype4";
	public static final String DEF17 = "def17";
	public static final String CUSTNAME = "custname";
	public static final String DEF11 = "def11";
	public static final String DEF14 = "def14";
	public static final String DEF7 = "def7";
	public static final String BALANCE = "balance";
	public static final String DEF16 = "def16";
	public static final String TS = "ts";
	public static final String DEF6 = "def6";
	public static final String FIRSTMNY = "firstmny";
	public static final String DEF15 = "def15";
	public static final String PK_CONTRACT = "pk_contract";
	public static final String DEF10 = "def10";
	public static final String DEF18 = "def18";
	public static final String DEF13 = "def13";
	public static final String DEF8 = "def8";
	public static final String CURRMNY = "currmny";
	public static final String DEF1 = "def1";
	public static final String PK_CUMANDOC = "pk_cumandoc";
	public static final String PK_SALE_BALANCE_B = "pk_sale_balance_b";
	public static final String DEF12 = "def12";
	public static final String DEF2 = "def2";
	public static final String CONCODE = "concode";
	public static final String DEF19 = "def19";
	public static final String DEF4 = "def4";
	public static final String DEF20 = "def20";
	public static final String ADTYPE2 = "adtype2";
	public static final String PK_SALE_BALANCE = "pk_sale_balance";
	public static final String DEF3 = "def3";
	public static final String DEF9 = "def9";

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性adtype3的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getAdtype3() {
		return adtype3;
	}

	/**
	 * 属性adtype3的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newAdtype3
	 *            UFDouble
	 */
	public void setAdtype3(UFDouble newAdtype3) {

		adtype3 = newAdtype3;
	}

	/**
	 * 属性salemny的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getSalemny() {
		return salemny;
	}

	/**
	 * 属性salemny的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newSalemny
	 *            UFDouble
	 */
	public void setSalemny(UFDouble newSalemny) {

		salemny = newSalemny;
	}

	/**
	 * 属性connamed的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getConnamed() {
		return connamed;
	}

	/**
	 * 属性connamed的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newConnamed
	 *            String
	 */
	public void setConnamed(String newConnamed) {

		connamed = newConnamed;
	}

	/**
	 * 属性salebalance的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getSalebalance() {
		return salebalance;
	}

	/**
	 * 属性salebalance的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newSalebalance
	 *            UFDouble
	 */
	public void setSalebalance(UFDouble newSalebalance) {

		salebalance = newSalebalance;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性adtype4的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getAdtype4() {
		return adtype4;
	}

	/**
	 * 属性adtype4的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newAdtype4
	 *            UFDouble
	 */
	public void setAdtype4(UFDouble newAdtype4) {

		adtype4 = newAdtype4;
	}

	/**
	 * 属性def17的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef17() {
		return def17;
	}

	/**
	 * 属性def17的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef17
	 *            String
	 */
	public void setDef17(String newDef17) {

		def17 = newDef17;
	}

	/**
	 * 属性custname的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getCustname() {
		return custname;
	}

	/**
	 * 属性custname的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newCustname
	 *            String
	 */
	public void setCustname(String newCustname) {

		custname = newCustname;
	}

	/**
	 * 属性def11的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef11() {
		return def11;
	}

	/**
	 * 属性def11的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef11
	 *            String
	 */
	public void setDef11(String newDef11) {

		def11 = newDef11;
	}

	/**
	 * 属性def14的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef14() {
		return def14;
	}

	/**
	 * 属性def14的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef14
	 *            String
	 */
	public void setDef14(String newDef14) {

		def14 = newDef14;
	}

	/**
	 * 属性def7的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef7
	 *            String
	 */
	public void setDef7(String newDef7) {

		def7 = newDef7;
	}

	/**
	 * 属性balance的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBalance() {
		return balance;
	}

	/**
	 * 属性balance的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newBalance
	 *            UFDouble
	 */
	public void setBalance(UFDouble newBalance) {

		balance = newBalance;
	}

	/**
	 * 属性def16的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef16() {
		return def16;
	}

	/**
	 * 属性def16的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef16
	 *            String
	 */
	public void setDef16(String newDef16) {

		def16 = newDef16;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDateTime
	 */
	public String getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(String newTs) {

		ts = newTs;
	}

	/**
	 * 属性def6的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef6
	 *            String
	 */
	public void setDef6(String newDef6) {

		def6 = newDef6;
	}

	/**
	 * 属性firstmny的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFirstmny() {
		return firstmny;
	}

	/**
	 * 属性firstmny的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newFirstmny
	 *            UFDouble
	 */
	public void setFirstmny(UFDouble newFirstmny) {

		firstmny = newFirstmny;
	}

	/**
	 * 属性def15的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef15() {
		return def15;
	}

	/**
	 * 属性def15的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef15
	 *            String
	 */
	public void setDef15(String newDef15) {

		def15 = newDef15;
	}

	/**
	 * 属性pk_contract的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getPk_contract() {
		return pk_contract;
	}

	/**
	 * 属性pk_contract的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newPk_contract
	 *            String
	 */
	public void setPk_contract(String newPk_contract) {

		pk_contract = newPk_contract;
	}

	/**
	 * 属性def10的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef10
	 *            String
	 */
	public void setDef10(String newDef10) {

		def10 = newDef10;
	}

	/**
	 * 属性def18的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef18() {
		return def18;
	}

	/**
	 * 属性def18的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef18
	 *            String
	 */
	public void setDef18(String newDef18) {

		def18 = newDef18;
	}

	/**
	 * 属性def13的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef13() {
		return def13;
	}

	/**
	 * 属性def13的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef13
	 *            String
	 */
	public void setDef13(String newDef13) {

		def13 = newDef13;
	}

	/**
	 * 属性def8的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef8
	 *            String
	 */
	public void setDef8(String newDef8) {

		def8 = newDef8;
	}

	/**
	 * 属性currmny的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getCurrmny() {
		return currmny;
	}

	/**
	 * 属性currmny的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newCurrmny
	 *            UFDouble
	 */
	public void setCurrmny(UFDouble newCurrmny) {

		currmny = newCurrmny;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性pk_cumandoc的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getPk_cumandoc() {
		return pk_cumandoc;
	}

	/**
	 * 属性pk_cumandoc的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newPk_cumandoc
	 *            String
	 */
	public void setPk_cumandoc(String newPk_cumandoc) {

		pk_cumandoc = newPk_cumandoc;
	}

	/**
	 * 属性pk_sale_balance_b的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getPk_sale_balance_b() {
		return pk_sale_balance_b;
	}

	/**
	 * 属性pk_sale_balance_b的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newPk_sale_balance_b
	 *            String
	 */
	public void setPk_sale_balance_b(String newPk_sale_balance_b) {

		pk_sale_balance_b = newPk_sale_balance_b;
	}

	/**
	 * 属性def12的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef12() {
		return def12;
	}

	/**
	 * 属性def12的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef12
	 *            String
	 */
	public void setDef12(String newDef12) {

		def12 = newDef12;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性concode的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getConcode() {
		return concode;
	}

	/**
	 * 属性concode的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newConcode
	 *            String
	 */
	public void setConcode(String newConcode) {

		concode = newConcode;
	}

	/**
	 * 属性def19的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef19() {
		return def19;
	}

	/**
	 * 属性def19的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef19
	 *            String
	 */
	public void setDef19(String newDef19) {

		def19 = newDef19;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性def20的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef20() {
		return def20;
	}

	/**
	 * 属性def20的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef20
	 *            String
	 */
	public void setDef20(String newDef20) {

		def20 = newDef20;
	}

	/**
	 * 属性adtype2的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return UFDouble
	 */
	public UFDouble getAdtype2() {
		return adtype2;
	}

	/**
	 * 属性adtype2的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newAdtype2
	 *            UFDouble
	 */
	public void setAdtype2(UFDouble newAdtype2) {

		adtype2 = newAdtype2;
	}

	/**
	 * 属性pk_sale_balance的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getPk_sale_balance() {
		return pk_sale_balance;
	}

	/**
	 * 属性pk_sale_balance的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newPk_sale_balance
	 *            String
	 */
	public void setPk_sale_balance(String newPk_sale_balance) {

		pk_sale_balance = newPk_sale_balance;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性def9的Getter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newDef9
	 *            String
	 */
	public void setDef9(String newDef9) {

		def9 = newDef9;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_sale_balance_b == null) {
			errFields.add(new String("pk_sale_balance_b"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-11-13
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "pk_sale_balance";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-11-13
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_sale_balance_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-11-13
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "ehpta_calc_sale_balance_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-11-13
	 */
	public SaleBalanceBVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newPk_sale_balance_b
	 *            主键值
	 */
	public SaleBalanceBVO(String newPk_sale_balance_b) {

		// 为主键字段赋值:
		pk_sale_balance_b = newPk_sale_balance_b;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_sale_balance_b;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @param newPk_sale_balance_b
	 *            String
	 */
	public void setPrimaryKey(String newPk_sale_balance_b) {

		pk_sale_balance_b = newPk_sale_balance_b;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-11-13
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {
		return "ehpta_calc_sale_balance_b";

	}
}
