/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.vo.hi.hi_401;

import nc.vo.pub.*;

/**
 * Setchg的聚合VO类。
 *
 * 创建日期：(2002-3-20)
 * @author：tianhb
 */
public class SetchgVO extends AggregatedValueObject {

	private SetchgHeaderVO header = null;
	private SetchgItemVO[] items = null;

	// 时间戳标示，现在暂未使用：
	long currentTimestamp; // 当前时间戳
	long initialTimestamp; // 从数据库读入时获得的时间戳
/**
 * SetchgVO 构造子注解。
 */
public SetchgVO() {
	super();
}
/**
 * <p>获得子表的VO数组。
 * <p>
 * 创建日期：(2002-3-20)
 * @return nc.vo.pub.CircularlyAccessibleValueObject[]
 */
public CircularlyAccessibleValueObject[] getChildrenVO() {

	return items;
}
/**
 * <p>获得母表的VO。
 * <p>
 * 创建日期：(2002-3-20)
 * @return nc.vo.pub.CircularlyAccessibleValueObject
 */
public CircularlyAccessibleValueObject getParentVO() {

	return header;
}

/**
 * <p>设置母表的VO。
 * <p>
 * 创建日期：(2002-3-20)
 * @param parent nc.vo.pub.CircularlyAccessibleValueObject
 */
public void setParentVO(CircularlyAccessibleValueObject parent) {

	header = (SetchgHeaderVO) parent;
}
/**
 * <p>设置子表的VO数组。
 * <p>
 * 创建日期：(2002-3-20)
 * @param children nc.vo.pub.CircularlyAccessibleValueObject[]
 */
public void setChildrenVO(CircularlyAccessibleValueObject[] children) {

	items = (SetchgItemVO[]) children;
}

	public String tablename="";

/**
 * <p>获得母表的VO。
 * <p>
 * 创建日期：(2002-3-20)
 * @return nc.vo.pub.CircularlyAccessibleValueObject
 */
public String getTablename() {

	return tablename;
}

/**
 * <p>获得母表的VO。
 * <p>
 * 创建日期：(2002-3-20)
 * @return nc.vo.pub.CircularlyAccessibleValueObject
 */
public void setTablename(String newtable) {

	tablename=newtable;
}
}