
package nc.itf.hr.hsdel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Oct 26 13:49:12 CST 2009
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CBOHRCBOHRSVIPersonDeleteSVDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {
    public static final long serialVersionUID = 20091026134912L;
    
    private nc.itf.hr.hsdel.ServiceLostException serviceLostException;

    public UFIDAU9CBOHRCBOHRSVIPersonDeleteSVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CBOHRCBOHRSVIPersonDeleteSVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CBOHRCBOHRSVIPersonDeleteSVDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CBOHRCBOHRSVIPersonDeleteSVDoServiceLostExceptionFaultFaultMessage(String message, nc.itf.hr.hsdel.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9CBOHRCBOHRSVIPersonDeleteSVDoServiceLostExceptionFaultFaultMessage(String message, nc.itf.hr.hsdel.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public nc.itf.hr.hsdel.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
