/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.yto.blacklist;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2011-8-26
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class HiPsndocBadAppHVO extends SuperVO {

	public String def5;
	public String pk_corp;
	public String vbusicode;
	public Integer dr;
	public String voperatorid;
	public String def17;
	public String vapprovenote;
	public String def11;
	public String pk_billtype;
	public String def7;
	public Integer vbillstatus;
	public String def14;
	public String def6;
	public String pk_busitype;
	public String ts;
	public String def16;
	public UFDate voperatordate;
	public String def15;
	public String vbillno;
	public String def10;
	public String def18;
	public String def13;
	public String def8;
	public String def1;
	public UFDate dapprovedate;
	public String pk_psndoc_bad;
	public String vapproveid;
	public String def2;
	public String def12;
	public String def4;
	public String def19;
	public String def20;
	public String def3;
	public String def9;

	public static final String DEF5 = "def5";
	public static final String PK_CORP = "pk_corp";
	public static final String VBUSICODE = "vbusicode";
	public static final String DR = "dr";
	public static final String VOPERATORID = "voperatorid";
	public static final String DEF17 = "def17";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String DEF11 = "def11";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String DEF7 = "def7";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String DEF14 = "def14";
	public static final String DEF6 = "def6";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String TS = "ts";
	public static final String DEF16 = "def16";
	public static final String VOPERATORDATE = "voperatordate";
	public static final String DEF15 = "def15";
	public static final String VBILLNO = "vbillno";
	public static final String DEF10 = "def10";
	public static final String DEF18 = "def18";
	public static final String DEF13 = "def13";
	public static final String DEF8 = "def8";
	public static final String DEF1 = "def1";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String PK_PSNDOC_BAD = "pk_psndoc_bad";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String DEF12 = "def12";
	public static final String DEF4 = "def4";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";
	public static final String DEF3 = "def3";
	public static final String DEF9 = "def9";

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性vbusicode的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getVbusicode() {
		return vbusicode;
	}

	/**
	 * 属性vbusicode的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVbusicode
	 *            String
	 */
	public void setVbusicode(String newVbusicode) {

		vbusicode = newVbusicode;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性def17的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef17() {
		return def17;
	}

	/**
	 * 属性def17的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef17
	 *            String
	 */
	public void setDef17(String newDef17) {

		def17 = newDef17;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性def11的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef11() {
		return def11;
	}

	/**
	 * 属性def11的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef11
	 *            String
	 */
	public void setDef11(String newDef11) {

		def11 = newDef11;
	}

	/**
	 * 属性pk_billtype的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getPk_billtype() {
		return pk_billtype;
	}

	/**
	 * 属性pk_billtype的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newPk_billtype
	 *            String
	 */
	public void setPk_billtype(String newPk_billtype) {

		pk_billtype = newPk_billtype;
	}

	/**
	 * 属性def7的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef7
	 *            String
	 */
	public void setDef7(String newDef7) {

		def7 = newDef7;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性def14的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef14() {
		return def14;
	}

	/**
	 * 属性def14的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef14
	 *            String
	 */
	public void setDef14(String newDef14) {

		def14 = newDef14;
	}

	/**
	 * 属性def6的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef6
	 *            String
	 */
	public void setDef6(String newDef6) {

		def6 = newDef6;
	}

	/**
	 * 属性pk_busitype的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getPk_busitype() {
		return pk_busitype;
	}

	/**
	 * 属性pk_busitype的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newPk_busitype
	 *            String
	 */
	public void setPk_busitype(String newPk_busitype) {

		pk_busitype = newPk_busitype;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return UFDateTime
	 */
	public String getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(String newTs) {

		ts = newTs;
	}

	/**
	 * 属性def16的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef16() {
		return def16;
	}

	/**
	 * 属性def16的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef16
	 *            String
	 */
	public void setDef16(String newDef16) {

		def16 = newDef16;
	}

	/**
	 * 属性voperatordate的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return UFDate
	 */
	public UFDate getVoperatordate() {
		return voperatordate;
	}

	/**
	 * 属性voperatordate的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVoperatordate
	 *            UFDate
	 */
	public void setVoperatordate(UFDate newVoperatordate) {

		voperatordate = newVoperatordate;
	}

	/**
	 * 属性def15的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef15() {
		return def15;
	}

	/**
	 * 属性def15的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef15
	 *            String
	 */
	public void setDef15(String newDef15) {

		def15 = newDef15;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性def10的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef10
	 *            String
	 */
	public void setDef10(String newDef10) {

		def10 = newDef10;
	}

	/**
	 * 属性def18的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef18() {
		return def18;
	}

	/**
	 * 属性def18的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef18
	 *            String
	 */
	public void setDef18(String newDef18) {

		def18 = newDef18;
	}

	/**
	 * 属性def13的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef13() {
		return def13;
	}

	/**
	 * 属性def13的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef13
	 *            String
	 */
	public void setDef13(String newDef13) {

		def13 = newDef13;
	}

	/**
	 * 属性def8的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef8
	 *            String
	 */
	public void setDef8(String newDef8) {

		def8 = newDef8;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性pk_psndoc_bad的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getPk_psndoc_bad() {
		return pk_psndoc_bad;
	}

	/**
	 * 属性pk_psndoc_bad的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newPk_psndoc_bad
	 *            String
	 */
	public void setPk_psndoc_bad(String newPk_psndoc_bad) {

		pk_psndoc_bad = newPk_psndoc_bad;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性def12的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef12() {
		return def12;
	}

	/**
	 * 属性def12的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef12
	 *            String
	 */
	public void setDef12(String newDef12) {

		def12 = newDef12;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性def19的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef19() {
		return def19;
	}

	/**
	 * 属性def19的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef19
	 *            String
	 */
	public void setDef19(String newDef19) {

		def19 = newDef19;
	}

	/**
	 * 属性def20的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef20() {
		return def20;
	}

	/**
	 * 属性def20的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef20
	 *            String
	 */
	public void setDef20(String newDef20) {

		def20 = newDef20;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性def9的Getter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newDef9
	 *            String
	 */
	public void setDef9(String newDef9) {

		def9 = newDef9;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_psndoc_bad == null) {
			errFields.add(new String("pk_psndoc_bad"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2011-8-26
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2011-8-26
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_psndoc_bad";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2011-8-26
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "hi_psndoc_bad_app_h";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2011-8-26
	 */
	public HiPsndocBadAppHVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newPk_psndoc_bad
	 *            主键值
	 */
	public HiPsndocBadAppHVO(String newPk_psndoc_bad) {

		// 为主键字段赋值:
		pk_psndoc_bad = newPk_psndoc_bad;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_psndoc_bad;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @param newPk_psndoc_bad
	 *            String
	 */
	public void setPrimaryKey(String newPk_psndoc_bad) {

		pk_psndoc_bad = newPk_psndoc_bad;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2011-8-26
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "hi_psndoc_bad_app_h";

	}
}
